### ISSUE TITLE
Unify refextract - maybe a separate service

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#1]
Unify the ref-extract between next and hep, one idea is to create a separate service

**Comment by MJedr** [comment]
**TECH NOTES**
1. refactor refextract to be a flask app, all the [api functions](https://github.com/inspirehep/refextract/blob/master/refextract/references/api.py) should have an endpoint
2. create an image for refextract - for sure it should have `poppler-utils` installed to make it work
3. Add a k8s app with a service and deployment based on refextract image. To discuss: do we want to expose a service outside of the cluster?
4. Refactor hep and next to use a new service

**Comment by michamos** [comment]
I suppose you've thought about this, but keep in mind that the complexity is not in refextract itself, but in the fact that it needs to receive the journal knowledge base as in https://github.com/inspirehep/inspirehep/blob/202b2e72acc16bc423190f6aa46d0184b90d3884/backend/inspirehep/editor/views.py#L255, which requires a DB read to be generated.
