### ISSUE TITLE
Claiming: add number of selected papers to the ui

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#10]
When selecting several papers on a profile, the number of selected papers should be displayed at the top, similarly to what happens for Literature search for curators so it's clear that selecting all only selects on the current page.

**Comment by drjova** [comment]
![Screenshot 2022-04-08 at 11 44 35](https://user-images.githubusercontent.com/4287772/162410706-8892761c-0e45-4c9b-bb08-1b44e27e7163.png)

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES: use NumberOfResultsWithSelectedItemsNumber component in Authors
