### ISSUE TITLE
Literature claim name check endpoint returns 500

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#100]
https://inspirebeta.net/api/assign/check-names-compatibility?literature_recid=2111572 returns a 500 for me

**Comment by MJedr** [comment]
**TECH NOTES**
1. Return [after this line](https://github.com/inspirehep/inspirehep/blob/2a3a9860bbffdd8813a19824e6a64f84859f30b0/backend/inspirehep/assign/utils.py#L82) if no hits, also change the check here (check for hits not needed) https://github.com/inspirehep/inspirehep/blob/2a3a9860bbffdd8813a19824e6a64f84859f30b0/backend/inspirehep/assign/utils.py#L83
