### ISSUE TITLE
`redirect_references_to_merged_record` takes too long for ES scroll

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#106]
https://sentry.sis.cern.ch/inspire/hep/issues/151496/?query=is%3Aunresolved

Sometimes, the task takes too much time and the scroll query expires.

**Comment by MJedr** [comment]
**TECH NOTES**
* [Here](https://github.com/inspirehep/inspirehep/blob/a6202ce99f5bad49ca3592f6ee609f4eb3fc5424/backend/inspirehep/records/tasks.py#L86) add `scroll` to search params `scroll="60m"`
