### ISSUE TITLE
disable scanned documents for fulltext (and grobid)

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#111]
Sometimes it might happen that the document pdf is scanned. Thus, it doesn't make much sense to index it as fulltext cause it won't provide any useful information and will cause redundancy in our index (note that some documents are big, almost 100 MB). Also, scanned pdfs broke workflows in grobid step. 
We should detect if the document is a scan and then don't include it in those two tasks.

**Comment by drjova** [comment]
Let's try to check the headers, and see if it improves the situation.

**Comment by MJedr** [comment]
blocked by #116
