### ISSUE TITLE
Change `stat.*` arXiv category translation

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#115]
Currently the `stat.*` arXiv categories gets translated to `Other` INSPIRE category. This should be changed to `Data Analysis and Statistics` instead in https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/utils.py#L127. The whole list of category names can be found in https://arxiv.org/archive/stat.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Add `stat` categories:
    * `stat.AP`
    * `stat.CO`
    * `stat.ML`
    * `stat.ME`
    * `stat.OT`
    * `stat.TH`
to [this mapping](https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/utils.py#L127).
They should be translated to `Analysis and Statistics`.
