### ISSUE TITLE
Update PDG identifiers

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#117]
We need to update the PDG identifiers based on https://pdg.lbl.gov/2022/pdgid/PDGIdentifiers-references-2022v0.json.

Some INSPIRE records have `keywords` with `schema=PDG`. Those should be updated so they reflect the previous list: any record mentioned in that list should have exactly the `keywords.value` from there, any record not in that list shouldn't have any PDG keywords.

Something similar needs to happen every 1-2 years when a new edition of the PDG appears, so it would be good to have something reusable.

**Comment by MJedr** [comment]
**TECH NOTES**
Write a cli in the curation module which will:
1. fetch the json file from PDG
2. Get the records that have any keywords with `schema=PDG`. Remove all the keywords with `schema=PDG` from them. If they're in the pdg json update the keywords with those listed in a file.

**Comment by michamos** [comment]
For 1. note that the actual URL will change next time, so it needs to be configurable.
2. misses the case of records that are now referenced in the PDG file but don't have PDG keywords yet.
