### ISSUE TITLE
add "publisher correction" to erratum keywords

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#12]
Some titles start with `Publisher correction` to signal that it's an erratum, but we don't currently detect that. We need to add it to https://github.com/MJedr/inspire-json-merger/blob/8fa59c53285872a5b864e4810b6a4eb90adffff3/inspire_json_merger/api.py#L148. After releasing `inspire-json-merge` update `inspire-next` to the latest version

**Comment by drjova** [comment]
We will need a bit more details :)

**Comment by michamos** [comment]
of course, I hope it's clear now.
