### ISSUE TITLE
Improve cite summary discoverability

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#121]
Currently the cite summary can be open through a toggle with a not super explict icon: 

![Image](https://user-images.githubusercontent.com/2895793/186424434-77db50c4-3789-4e98-8382-9fc04c8e6d86.png)

We often hear feedback that users don't know about this feature. The problem is it's not very discoverable, we should improve it.

**Comment by drjova** [comment]
Add a label next to the citation summary button:

![Image](https://user-images.githubusercontent.com/4287772/188115837-d4d9e5f7-4e8f-444d-8306-61dcbc296bcb.png)
