### ISSUE TITLE
change non-core relevance scoring

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#123]
from discussion in https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/relevance.20sorting/near/294100414:

We should change how the `relevance_score` gets computed in https://github.com/inspirehep/inspire-next/blob/ce75d58fb47679fb4de55551b6aa9918b3d0e0ae/inspirehep/modules/workflows/tasks/classifier.py#L87-L91. It should stay as currently when `decision` is `CORE` or `Rejected`, but when decision is `Non-CORE`, it should be:
```python
relevance_score = 0.5*scores["Non-CORE"] + scores["CORE"]
```
in order to take into account also the distance to CORE/Rejected.

**Comment by drjova** [comment]
TECH NOTES:

* Add [here](https://github.com/inspirehep/inspire-next/blob/ce75d58fb47679fb4de55551b6aa9918b3d0e0ae/inspirehep/modules/workflows/tasks/classifier.py#L90) another `else if` to check if `Non-CORE` and if it is update the `relevance_scrore` with the equation in the description.
