### ISSUE TITLE
add fulltext snippet preview

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#124]
The AB reports that it would be good to display a snippet from the fulltext with the context when doing fulltext search, similarly to what google does:

![Image](https://user-images.githubusercontent.com/2895793/186427426-34060a63-cf10-4439-a038-10cf0870dae3.png)

This can be done using an [ES highlighter](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html). Note that we want to highlight only in the fulltext, not other fields.

We need to discuss how the UI would look.

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES: 

1. Create FulltextSnippet.tsx component to display fulltext snippet stored in record's metadata (const fulltextSnippet = metadata.get('fulltext_highlight');
2. In [LiteratureItem.jsx](https://github.com/inspirehep/inspirehep/blob/b9bc282d431fb292d9ffb8658d2101080d4f9bf2/ui/src/literature/components/LiteratureItem.jsx#L209) component in the bottom of the card (below `<PublicNotesList />` component) add <FulltextSnippet.tsx /> component
3. Component should look like on the provided screen.

![image](https://user-images.githubusercontent.com/55505399/191494899-1192d2ab-0656-4830-8552-7c69929ebc73.png)
