### ISSUE TITLE
create UI for reference search

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#125]
after #102 is added, we need to add some UI to make it accessible from the reference list in a paper.

**Comment by drjova** [comment]
The idea is to add a new link as `Citations` in detail and list views

**Comment by michamos** [comment]
It should look like this, and link to a `citedby:recid:{current_recid}` search.

![Image](https://user-images.githubusercontent.com/2895793/194343589-6982c2ff-90bb-4e83-acad-ffa04a64e031.png)

**Comment by drjova** [comment]
@michamos is this the final version?

**Comment by michamos** [comment]
yes, it is!

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**

1.  In[ utils.js](https://github.com/inspirehep/inspirehep/blob/335b060eaf1814c4c17708bbad5730aa0ed16fe3/ui/src/literature/utils.js) create new method getReferenceSearchQuery similar to ```getPapersQueryString``` that returns  ```citedby:recid:{current_recid} ```
2. Create <ReferenceSearchLinkAction /> component similar to [IncomingLiteratureReferencesLinkAction](https://github.com/inspirehep/inspirehep/blob/bf5025906d19daf5dc018407a280321d6eb849fa/ui/src/common/components/IncomingLiteratureReferencesLinkAction.jsx)
3. Add the above component to rightActions in [LiteratureItem](https://github.com/inspirehep/inspirehep/blob/a4bb802003520e616515d74a3b5696089ce3c72a/ui/src/literature/components/LiteratureItem.jsx) and [DetailPageContainer](https://github.com/inspirehep/inspirehep/blob/69bcc2bb607babb0733cf4ceb1c9e6650752b780/ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx)
