### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#136]
We want to redesign the homepage in order to:

* Make the collaboration institutions more visible
* Have a place to present news from the INSPIRE blog

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**

1. Move 'how to search' section to the bottom, instead add 'How to search' link button with scroll underneath search bar
2. Collaborations section
 - Move the section up, right after search bar, delete 'Collaborations' title and add smaller one saying 'Brought to you by', decrease collaboration logos height to 40px
3. Create 'News & updates' section with 3 latest inspire blog posts (data from ...). The 'news' component should look like most of the search items across the application. It should contain title, description, date and link to the article on inspire blog. Underneath there should be a link button redirecting to all inspire blog posts.
