### ISSUE TITLE
Gracefully handle wrong ISO date in APS harvest

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#138]
See https://sentry.sis.cern.ch/inspire/hepcrawl/issues/181881/?query=is%3Aunresolved:

We're trying to parse something as an ISO date in https://github.com/inspirehep/hepcrawl/blob/master/hepcrawl/parsers/jats.py#L426 but sometimes it's not actually an ISO date. We should handle that gracefully and intercept the raised exception, as we're trying to build a date from other metadata later in the same method.

Once it's fixed, we should reharvest affected journals since the bug started occuring.

**Comment by MJedr** [comment]
@michamos do you know the exact date? or should I run it from the date when the bug appeared, so from May 3?

**Comment by michamos** [comment]
that looks like the safest option. When do you plan to run it? I want to give a heads up to curators.
