### ISSUE TITLE
disambiguation fails sometimes because of `RequestError`

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#139]
Sometimes disambiguation fails sometimes because of `RequestError`. Maybe it would be enough to retry the task on this error.
https://sentry.sis.cern.ch/inspire/hep/issues/231632/?query=is%3Aunresolved%20RequestError

**Comment by drjova** [comment]
TECH NOTES:

* Unify the retry policy for all the tasks.
* Retry [here](https://github.com/inspirehep/inspirehep/blob/52ec7583e80fa92118036b4a4d16b8103c3ca0a1/backend/inspirehep/disambiguation/tasks.py#L311-L318) on RequestError
