### ISSUE TITLE
allow editor upload for any user with edit rights, not only curators

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#142]
Currently only curators are allowed to use the editor upload functionality. This should be changed so any user with a `*-read-write` role is allowed to perform uploads too, as they have access to the editor.

**Comment by nooraangelva** [comment]
**TECH NOTES:**
- Change [here](https://github.com/inspirehep/inspirehep/blob/8a0e6f3e7b22c863e1812b84cd230412a4ca68a5/backend/inspirehep/editor/views.py#L307) the login/user check to this:
```
from inspirehep.accounts.api import check_permissions_for_private_collection_read_write
@blueprint.route("/<endpoint>/<int:pid_value>/upload", methods=["POST"])
@login_required
pid_type = PidStoreBase.get_pid_type_from_endpoint(endpoint)
 record = InspireRecord.get_record_by_pid_value(pid_value, pid_type, original_record=True)
if not check_permissions_for_private_collection_read(record.get("_collections", [])):
return jsonify(message="Unauthorized", code=403), 403
```
Add new path [here](https://github.com/inspirehep/inspirehep/blob/8a0e6f3e7b22c863e1812b84cd230412a4ca68a5/record-editor/src/app/core/services/common-api.service.ts#L66) ``` //${editorApiUrl}/${pidType}/${pidValue}/upload```
- Create tests like [this](https://github.com/inspirehep/inspirehep/blob/8a0e6f3e7b22c863e1812b84cd230412a4ca68a5/backend/tests/integration/editor/test_editor_views.py#L558) and [this](https://github.com/inspirehep/inspirehep/blob/8a0e6f3e7b22c863e1812b84cd230412a4ca68a5/backend/tests/integration/editor/test_editor_views.py#L511)
