### ISSUE TITLE
Log record used for affiliation normalization

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#145]
During affiliation normalization, it would be useful to preserve more information about why the affiliation was assigned. We should log the record ID of the match that was used as well as the normalized and raw affiliations that were used.

**Comment by MJedr** [comment]
**TECH NOTES**
We already have logging for that event, the issue is with an incorrect setting for the logger. 
Change `LOGGING_CONSOLE_LEVEL` app config setting to `INFO`
