### ISSUE TITLE
strip MathML tags in LaTeX/BibTeX formats

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#147]
We've recently stopped stripping mathml in titles. However, this has the unfortunate side effects of causing all the XML markup to appear in the LaTeX/BibTeX output formats. We should modify those to strip all the markup for now, keeping the contents, similarly to what was done in hepcrawl before https://github.com/inspirehep/hepcrawl/pull/320.

**Comment by MJedr** [comment]
**TECH NOTES**
* strip mathml tags with [`remove_tags`](https://github.com/inspirehep/inspire-utils/blob/b07397c7f7f1f9871d01f3d934f2d4e8678a8c7b/inspire_utils/helpers.py#L113) [here](https://github.com/inspirehep/inspirehep/blob/a6202ce99f5bad49ca3592f6ee609f4eb3fc5424/backend/inspirehep/records/marshmallow/literature/bibtex.py#L229) anad [here](https://github.com/inspirehep/inspirehep/blob/a6202ce99f5bad49ca3592f6ee609f4eb3fc5424/backend/inspirehep/records/marshmallow/literature/latex.py#L83)
