### ISSUE TITLE
Implement processing xml files in Elsevier spider

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#158]
Currently Elsevier spider process only files from provided in Elsevier batch feed (they are packed in zip files). We should add a functionality to process selected xml file (should be parsed and converted to INSPIRE record).

What we would need is a way to reharvest a given record, but we need to be able to provide it as an input to scrapy.

**Comment by MJedr** [comment]
**TECH NOTES**
* Create a new spider `elsevier single`, which will inherit from the elsevier spider. It should allow passing additional parameter - `identifier`.
* Add a method that will search for the given document in s3. If it is found, a callback should be `parse_record`.
* Add a method `start_requests` which will call a new method as a callback.
* Add a config on k8s for this spider.
