### ISSUE TITLE
Journal collection: number of papers and embed view of literature papers - backend

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#159]
Backend for https://github.com/cern-sis/issues-inspire/issues/71

**Comment by MJedr** [comment]
**TECH NOTES**
* add a new table `JournalLiterature` with `journal_uuid` and `literature_uuid`
* add a mixin `JournalPapersMixin` with all the crud methods
* create alembic migration
* add a property to JournalRecord `number_of_papers`
* add `number_of_papers` to the marshmallow raw schema
* upgrade alembic on qa & prod after deployment
