### ISSUE TITLE
Add matomo events for all clickable UI elements

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#166]
We've added many UI elements recently, for example for claiming, but they don't correspond to events in Matomo. All these clickable UI elements should have corresponding matomo events so we can have analytics on their usage.

Also it's a bit difficult to understand which events are currently defined, naming is not super explicit or consistent. We also have an event that shows up as Event Name not defined. Could we maybe reorganize things a bit?

Besides events, one thing that we lost in the update to matomo is the custom variables to distinguish curators/admins from regular users (replaced by custom dimensions). It would be good to bring this back and add additional variables for various states of the UI (cite-summary open/closed, number of results/page, preferred citation format, etc.) to be able to know how people use INSPIRE. 

https://matomo.org/faq/reports/the-anatomy-of-an-event/

**Comment by drjova** [comment]
We should add custom events for the following:

* Claiming buttons (each case separately) in Literature and Authors
* Reference search button

Do I miss something @michamos ?

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES**

1. Wrap following components
- [AssignLiteratureItem](https://github.com/inspirehep/inspirehep/blob/0218ddefe73ed88279e29488d3ad798c91c91d26/ui/src/literature/components/AssignLiteratureItem.tsx) 
- [AssignOwnProfileAction](https://github.com/inspirehep/inspirehep/blob/1dcfbe164f0595b732473b05d4d0fd738554d19e/ui/src/authors/components/AssignOwnProfileAction.jsx)
- [AssignOneDifferentProfileAction](https://github.com/inspirehep/inspirehep/blob/1dcfbe164f0595b732473b05d4d0fd738554d19e/ui/src/authors/components/AssignOneDifferentProfileAction.jsx)
- [AssignAction](https://github.com/inspirehep/inspirehep/blob/1dcfbe164f0595b732473b05d4d0fd738554d19e/ui/src/authors/components/AssignAction.jsx)
with [<EventTracker />](https://github.com/inspirehep/inspirehep/blob/e71ff36163c395bbdeb9945ca9b82a8679c1823e/ui/src/common/components/EventTracker.jsx). Add meaningful event ID names in the following convention ```Functionality Name - Action Performed```
2. Change Reference search button event ID name from Reference:Search to Reference - Search.
