### ISSUE TITLE
In APS harvests, `Physics` journal should be `APS Physics`

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#170]
There are unfortunately several journals named `Physics`, which we distinguish as `APS Physics` and `MDPI Physics`. The journal named `Physics` is not an actual journal but just a way to avoid errors in cases of ambiguity. When harvesting APS, we know that a journal title in `publication_info` always refers to `APS Physics`, so we should translate `publication_info.journal_title:Physics` into `publication_info.journal_title:APS Physics` (not for references!).

**Comment by MJedr** [comment]
**TECH NOTES**
1. modify [the function here](https://github.com/inspirehep/hepcrawl/blob/2dfb8fbe9311b0627399b5a1547f8e6634c6073c/hepcrawl/parsers/jats.py#L201-L207) to add a journal_title `APS Physics` when journal title is `Physics`
2. Write a cli that will retrieve all the papers with source `APS` and title `Physics` and modify the journal_title accordingly.

**Comment by MJedr** [comment]
@michamos do we want to update metadata in existing records?

**Comment by michamos** [comment]
that's a good idea :+1: No need to write a CLI, a curation script would work fine.
