### ISSUE TITLE
Matomo custom event with user role doesn't work

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#171]
https://github.com/inspirehep/inspirehep/blob/master/ui/src/tracker.js#L46-L49 this part of the code doesn't set the user role anymore, this is might be due to the piwik-matomo compatibility.

**Comment by karolina-siemieniuk-morawska** [comment]
User role is now visible in Visit log 

![Image](https://user-images.githubusercontent.com/55505399/199519014-77b305c3-3e53-4f22-b3de-c7b1593936bc.png)
