### ISSUE TITLE
For proceedings, rename `Contribution to` -> `Proceedings of`

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#172]
See https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/Proceedings/near/305175617

For proceedings (`document_type:Proceedings`), it doesn't make sense to have the conference preceded by `Contribution to` in the display (as it's not a contribution, but the full proceedings). Instead, it should be `Proceedings of`.

**Comment by MJedr** [comment]
**TECH NOTES**
Change the label [here](https://github.com/inspirehep/inspirehep/blob/62766b035cc0f110d32b53adc5ab41327caec807/ui/src/literature/components/ConferenceInfoList.jsx#L14) to `Proceedings of`
