### ISSUE TITLE
SNOW: check API to replace RT

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#184]

**Comment by MJedr** [comment]
- [ ] Create the sandbox env for inspirebeta - check the docs https://cern.service-now.com/service-portal?id=kb_article&n=KB0007714
- [ ] Check if all the fields we use in RT can be mapped to SNOW fields, if not ask SNOW team to handle this
https://docs.servicenow.com/bundle/sandiego-application-development/page/integrate/inbound-rest/concept/c_RESTAPI.html
https://docs.servicenow.com/bundle/sandiego-application-development/page/integrate/inbound-rest/concept/c_TableAPI.html

**Comment by drjova** [comment]
- [ ] Record editor fix for handling display of the SNOW tickets.
