### ISSUE TITLE
Remove `FEATURE_FLAG_ENABLE_REFEXTRACT_SERVICE` feature flag

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#186]
We don't need this feature flag anymore:

https://github.com/inspirehep/inspirehep/blob/8a0e6f3e7b22c863e1812b84cd230412a4ca68a5/backend/inspirehep/editor/views.py#L257

**Comment by MJedr** [comment]
**TECH NOTES**
1. Remove the flag [from here](https://github.com/inspirehep/inspirehep/blob/8a0e6f3e7b22c863e1812b84cd230412a4ca68a5/backend/inspirehep/editor/views.py#L257)
2. Remove the flag from tests
3. Delete the flag from kustomization in k8s
