### ISSUE TITLE
Gracefully handle search queries

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#189]
search typos and wrong dates return 500 to users, we should gracefully handle these cases. Example: https://sentry.sis.cern.ch/inspire/hep/issues/236453/?query=is%3Aunresolved

**Comment by MJedr** [comment]
After changes in #190 we receive an error message in json. If the user enters a wrong query we will receive the message `"The syntax of the search query is invalid."`. We need to display it to the user.

**Comment by drjova** [comment]
@MJedr do we have a quick example?

**Comment by MJedr** [comment]
https://inspirebeta.net/api/literature?sort=mostrecent&size=25&page=1&q=f%20a%20zwicky%2C.
