### ISSUE TITLE
handle gracefully records with no authors in disambiguation

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#21]
see https://sentry.sis.cern.ch/inspire/hep/issues/41308/?query=is%3Aunresolved due to some records having no `authors` field.

**Comment by MJedr** [comment]
change [here](https://github.com/inspirehep/inspirehep/blob/485560855e47e441d3cc90e1faa3e470b7f708d6/backend/inspirehep/disambiguation/tasks.py#L238) to `authors = record.get("authors)`
