### ISSUE TITLE
Strip trailing whitespace in submission forms

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#212]
Sometimes users copy/paste info to submission fields (e.g. email addresses). This can include whitespace, but the field will then contain incorrect data and/or fail validation if we include the whitespace. We should strip all whitespace before/after the text in text fields to prevent this issue that sometimes confuses users.

**Comment by karolina-siemieniuk-morawska** [comment]
**Tech notes:**

In Inspire forms with yup validation schemas (submissions, change email), add .trim() method to all text fields.
