### ISSUE TITLE
deal with arXiv DOIs in references

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#218]
arXiv have added DOIs some time ago, derived from the arXiv ID. We don't currently support them, but they are starting to appear in references. It would be good to support them somehow to link references properly.

One option would be to translate them into arXiv IDs automatically in the reference builder. A more general approach would be to systematically add arXiv DOIs to all our records, but that's a bigger change.

**Comment by MJedr** [comment]
@michamos can you add more details about the the arxiv doi schema and translation to arxiv ID?

**Comment by MJedr** [comment]
**TECH NOTES**
1. Add a new regex for this kind of identifier
2. [Modify `is_arxiv`](https://github.com/inspirehep/inspire-schemas/blob/779702c751789b0a59cf925afaf0384311443304/inspire_schemas/utils.py#L1067) to take into consideration a new regex
3. Add a new option in [normalize_arxiv](https://github.com/inspirehep/inspire-schemas/blob/779702c751789b0a59cf925afaf0384311443304/inspire_schemas/utils.py#L1092) that will handle new arxiv id format

**Comment by MJedr** [comment]
@michamos so it has to be `10.48550/arXiv:{arxiv_id}` or `10.48550/arXiv.{arxiv_id}` (as in example)?

**Comment by michamos** [comment]
sorry, the example was copy/pasted and is correct, I mistyped the pattern
