### ISSUE TITLE
Don't return `links` header in REST API

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#221]
this header can become very large for large queries, which blows the HAProxy buffer, see discussion in https://cern-rcs-sis.zulipchat.com/#narrow/stream/310485-inspire/topic/bad.20gateway.20for.20API.20query/near/320975155.

The solution would be not to generate this header in the first place instead of stripping it at the ingress level.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Don't add links generated by `inspire_search_links` - [remove this line](https://github.com/inspirehep/inspirehep/blob/d9f3a1d856f7cc96070b2b8f72e3204cee1c41c5/backend/inspirehep/serializers.py#L80)
