### ISSUE TITLE
Create a backend for changing user emails

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#222]
Currently, users can have email addresses listed in two places:

author record (if they have one): this is either private or publicly visible, and is mainly meant for disambiguation or to be contacted by other INSPIRE users.
user account (if they have one): this is entered during account creation, then never shown again anywhere, and used to contact users by email automatically from the system (e.g. job ad closing, submission confirmation, etc.).
The problem with the user account email address is that there is currently no way for users to see or update it, so we very often have outdated email addresses when users change institutions (unlike the author record emails, which can be updated through the author form). We should have a way for users to see and update this information.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Add a new endpoint in `account` views. The new endpoint should:
    - update `email` field in the table `accounts_user`
    - check if the current user has an author profile - if yes, the new email should be added to `email_addresses` with `current=True` and all the emails in the `email_addresses` should be remarked as not current.

**Comment by michamos** [comment]
We want to keep also the previous email addresses in `email_addresses`. Note that a user can have several `current=True` emails, so it's not a good mechanism to select to accounts email.

**Comment by MJedr** [comment]
@michamos yes, we'll change also the value in `accounts_user`, is that ok? and also, if we keep the old one in `email_addresses`, do we change `current` to False?

**Comment by michamos** [comment]
there is no way to know whether we should change `current` to False for the previous one, so I would say no. Did we decide how the UI would look, I don't remember it? Maybe it makes sense to define that first?

**Comment by drjova** [comment]
@MJedr I would name it as the following: https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/accounts/views.py#L81

`/settings/update-email`
