### ISSUE TITLE
Display other persistent identifiers on records

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#224]
Many theses have [HDL](https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=persistent_identifiers.schema%3AHDL) or [URN](https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=persistent_identifiers.schema%3AURN) persistent identifiers which are currently not displayed on records.

We should display them similarly to DOIs on the detailed view,

> URN/HDL: {persistent_identifiers.value}

with a link to https://hdl.handle.net/{persistent_identifiers.value} in case of HDL (URN is not linkable).

**Comment by karolina-siemieniuk-morawska** [comment]
Tech notes:

1. Create new component <PersistentIdentifiers /> displaying text or link if identifier is HDL.
2. In [<DetailPageContainer />](https://github.com/inspirehep/inspirehep/blob/7d651a8a17a28b61857a4d162c8ae2bfb5561b99/ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx) under <DOIList /> add <PersistentIdentifiers />.
