### ISSUE TITLE
Harvest jsonlines instead of XML from DESY

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#228]
As discussed in https://inspirehep.zulipchat.com/#narrow/stream/122199-ops/topic/DESY.20harvest/near/322229993, DESY will start pushing JSON records to us instead of XML in the form of jsonlines files (one JSON record per line). The DESY spider in hepcrawl needs to be modified to support this new format.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Modify parse method of the spider:
  * [here](https://github.com/inspirehep/hepcrawl/blob/96b4dfcf9218b15e3f80016e7626d183ee6b3355/hepcrawl/spiders/desy_spider.py#L181) get json items from jsonline file (can be done with jsonlines library)

2. Replace [converting marcxml to json here](https://github.com/inspirehep/hepcrawl/blob/96b4dfcf9218b15e3f80016e7626d183ee6b3355/hepcrawl/spiders/desy_spider.py#L251) - we will iterate over json objects, so no need for the type conversion. Pass the json object directly to `ParsedItem`

3. Change naming for the methods and remove `marcxml` leftovers

**Comment by michamos** [comment]
Note that this should not be released in prod until they are ready at DESY to make the change.

**Comment by MJedr** [comment]
@michamos can you provide an example jsonline file for tests?
