### ISSUE TITLE
handle authorSuffix in author.xml

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#236]
We don't handle the `authorSuffix` in the author.xml format currently. Example:

```xml
      <foaf:Person>        
        <foaf:name>Michael Finger</foaf:name>        
        <foaf:givenName>Michael</foaf:givenName>        
        <foaf:familyName>Finger</foaf:familyName>        
        <cal:authorNameNative lang=""/>        
        <cal:authorSuffix>Jr.</cal:authorSuffix>        
        <cal:authorStatus/>        
        <cal:authorNamePaper>M. Finger Jr.</cal:authorNamePaper>        
        <cal:authorAffiliations>          
          <cal:authorAffiliation organizationid="o27" connection=""/>          
          <cal:authorAffiliation organizationid="vo1" connection="AlsoAt"/>          
        </cal:authorAffiliations>        
        <cal:authorIDs>          
          <cal:authorID source="INSPIRE">INSPIRE-00171357</cal:authorID>          
          <cal:authorID source="CCID">391883</cal:authorID>          
          <cal:authorID source="ORCID">0000-0003-3155-2484</cal:authorID>          
        </cal:authorIDs>        
      </foaf:Person>   
```
here, the name in the record should be `Finger, Michael, Jr.`.

**Comment by MJedr** [comment]
@michamos can you give us an example of the record where it is incorrect? cause in the code it looks ok, at least for the xml sample you posted here
https://github.com/inspirehep/inspire-next/blob/c04e0d2385104b4af9f227d9e7c9a3ebb82e8a6f/inspirehep/modules/workflows/tasks/arxiv.py#L338

**Comment by michamos** [comment]
@MJedr sorry, copy/pasted the wrong thing :facepalm: This is how it will look, with the `Jr.` only in the `authorSuffix`, not in`familyName`.

**Comment by MJedr** [comment]
**TECH NOTES**
Extract a suffix from `authorSuffix` and add it to the formatted name [here](https://github.com/inspirehep/inspire-next/blob/c04e0d2385104b4af9f227d9e7c9a3ebb82e8a6f/inspirehep/modules/workflows/tasks/arxiv.py#L338)
