### ISSUE TITLE
update IN2P3 logo

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#240]
IN2P3 has a new logo, it should be updated on the main website and on the blog.

color: ![Image](https://user-images.githubusercontent.com/2895793/221907392-ea08d169-d314-454c-92ab-23be00381154.png)
monochrome (for dark background): ![Image](https://user-images.githubusercontent.com/2895793/221907391-3cb82ae5-f6f6-4cff-b80e-588c3be586f9.png)

**Comment by karolina-siemieniuk-morawska** [comment]
Changed to new logos 
<img width="1051" alt="Screenshot 2023-03-02 at 14 38 02" src="https://user-images.githubusercontent.com/55505399/222444184-230febc1-ed34-4213-8ee2-08b49810e3bf.png">
<img width="841" alt="Screenshot 2023-03-02 at 14 48 04" src="https://user-images.githubusercontent.com/55505399/222446469-227927b2-066f-439d-8796-c15a9b26cef6.png">
