### ISSUE TITLE
integrate record-editor with snow api

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#241]
Currently, record-editor is designed in a way to support RT tickets. However, since we are introducing SNOW, which has a slightly different API, we need to adjust record-editor to support it.

We need to add a schema for a ticket, like [this one](https://github.com/inspirehep/inspirehep/blob/master/record-editor/src/app/shared/interfaces/ticket.ts), but the fields SNOW expects are:
- functional_category
- subject
- description
- recid
- assigned_to_email
- date
- link

Then, some small changes have to be done:
- [here](https://github.com/inspirehep/inspirehep/blob/a1e5a17fcd29b9fe4a8eb4b7ddfdaf7623290367/record-editor/src/app/shared/components/tickets/ticket/ticket.component.html#L2) use `functional_category` instead of `queue`
- [here](https://github.com/inspirehep/inspirehep/blob/a1e5a17fcd29b9fe4a8eb4b7ddfdaf7623290367/record-editor/src/app/shared/components/tickets/tickets.component.ts#L86) we don't want to check for the queue but for functional_category of the ticket.

Ideally, we should change method names to use `SNOW` instead of `RT`. Also, whenever we'll be ready, we should rename endpoints to `SNOW`, and in a payload of a new ticket we should put `assigned_to_email` instead of `owner`, as well as `functional_category` instead of `queue`.

**Comment by karolina-siemieniuk-morawska** [comment]
![Image](https://user-images.githubusercontent.com/55505399/223753486-346afb2d-5e4a-436e-b21c-99ce40f8a52e.png)
