### ISSUE TITLE
refactor `redirect_references_to_merged_record`

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#246]
We should refactor this task:
- don't run everything in one transaction
- change the queue
- change the number of retries
- remove `acks_late`

**Comment by michamos** [comment]
removing `acks_late` seems dangerous, unless there's a very good reason, all tasks should have `acks_late` I think (otherwise worker failing during a task will cause the task to be considered as succesful).

**Comment by MJedr** [comment]
actually, as far as I checked majority of our tasks don't have `acks_late`

**Comment by michamos** [comment]
then those might need to be changed :) it's particularly important for tasks modifying the DB, as if they feel we get inconsistent data.
On that topic, it's probably useful to add a CLI tool that takes all records in the pidstore that are redirected and run the task on them to make the database consistent (given many of these tasks have failed in the past).
