### ISSUE TITLE
Self curation - Diff interface for curators to see the differences between two versions

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#254]
# Requirements

The curators should be able to see the current version and the previous version of the modified referenced rendered and its metadata.

The curator would need to see 3 pieces of information:
1. The previous formatted reference
2. The new formatted reference
3. The raw metadata in the reference (formatted in some way) including raw reference

With this information, they should be able to revert the changes in the editor if needed.
Add provenance of reference correction to the entry (i.e. ORCID) to keep track of changes → privacy concern and how to filter it out so it’s not displayed in API

# Acceptance
* The curator be able to see the difference between two versions references
* If they want to revert the change be able to open the record on the editor and do it

**Comment by michamos** [comment]
Here's a basic mockup:

![Image](https://user-images.githubusercontent.com/2895793/228881853-6d31037e-732a-47bc-85e2-fbcdd706779b.png)

It displays:
1. the detailed view card on the top
2. the index of the changed reference
3. the user making the change
4. the formatted current reference (in the version corresponding to the change the user made)
5. the formatted previous reference (from the version before the change)
6. the formatted metadata (the reference as it would be formatted if it was unlinked)
7. the raw reference string (`references[i].raw_refs.text[0]`)

If the previous version was unlinked, there's no need to display 5. as it will be the same as 6.
