### ISSUE TITLE
investigate the removal of `signature_block`

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#258]
We should also remove the Beard dependencies and code and as a second step `signature_block`

**Comment by drjova** [comment]
@michamos do we need to keep signature_block?

**Comment by michamos** [comment]
No, we can remove it, it's a leftover from the BEARD approach to disambiguation. This will remove a lot of external dependencies (scikit-lean, numpy, etc.). Note that you can also remove all the BEARD related code we still have.
