### ISSUE TITLE
Remove migrator module

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#271]
Remove migrator module from hep, it's no longer needed 🎉

**Comment by drjova** [comment]
@michamos what you want to do about ` LegacyRecordsMirror`? We want to remove all the references from the code, is it ok if we take a final back-up to EOS and completely remove the table?

**Comment by michamos** [comment]
You can remove it from the code, but I'd like to keep a copy of the data easily accessible. For example a bunch of XML files somewhere, not a DB dump that requires complex operations to load into a DB and access.

**Comment by drjova** [comment]
Export the rows in xml and upload them to S3

**Comment by drjova** [comment]
TECH NOTES:

* From table `legacy_records_mirror` export the each row of `marcxml` column into an XML file and upload them to `inspire-{qa|prod}-legacy` bucket on S3. 
  * First try on QA and the run the script on PROD
* When the above is done, make a PR to completely remove the `migrator` module and any code reference.
