### ISSUE TITLE
Reprocess all quant-ph harvested as core

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#274]
Between the arXiv harvests on 2021-10-21 and 2022-11-16 (excluded), we considered all of  `quant-ph` as automatically core. We have since refined the definition of core, but all those records are still flagged as core, which we want to change. This requires to:
* remove `core=true` from all records created from these harvests
* manually check whether they should be core. Ideally, this would use the core selection workflow. However, if we want to use that, we'd need to reharvest all records (to run invenio-classifier with the updated ontology) and adapt the logic to ensure that they create a core selection workflow even they are updates and not new records.

This is the list of affected records: https://inspirehep.net/literature?sort=mostrecent&size=250&page=1&q=arxiv_eprints.categories%3Aquant-ph%20core%3Atrue%20not%20_desy_bookkeeping.status%3Afinal%20%20not%20_desy_bookkeeping.status%3Aprinted&earliest_date=1930--2022

**Comment by MJedr** [comment]
**TECH NOTES**
1. Get the list of affected recids from the provided query (with arxiv id)
2. Write a curation script to remove core=true from the records matching a query 
3. Reharvest all the articles saved in step one
4. Get list of created workflows and create out of them core selection workflows

**Comment by drjova** [comment]
@MJedr can we close this one?
