### ISSUE TITLE
Add dots to Citations per year graph

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#276]
![image](https://user-images.githubusercontent.com/55505399/229731368-b6be09f4-d0ff-47b2-b456-e367a3d0092b.png)

Also add tooltip to current year part of the graph.

**Comment by drjova** [comment]
Ask @michamos if we need a final approval before deploying

**Comment by michamos** [comment]
No, it's ok, I trust your aesthetic opinions :)

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES:

1. Add tooltip to current year graph - in [CitationsByYear](https://github.com/inspirehep/inspirehep/blob/a32488576e8b4a208554fc096d1d4dc607d27539/ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.tsx) component line 142 add `onNearestX={onGraphMouseOver}`
2. Change `<LineSeries />` components to `<LineMarkSeries />` components to add dots to graph (http://uber.github.io/react-vis/documentation/series-reference/line-mark-series)
