### ISSUE TITLE
backend: endpoint to return the diff of references for self curation interface

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#279]
```GET /api/literature/12333/diff/1..2```

```json
{
current_version: {reference_changed},
previous_version: {reference_changed},
}
```

**Comment by MJedr** [comment]
**TECH NOTES**
1. Create an endpojnt `/api/literature/<recid>/<version_1>..<version_2> (GET)`,  in `/records/views.py`
* inside of the endpoint fetch record in given versions and get the diff between them (create a helper method in `LiteratureRecord` that will check the diff between references and return the index of the changed reference, something like `get_modified_authors()`) 
* get reference object that changed from the previous and current versions and return it in a form 
```
{
current_version: {reference_changed},
previous_version: {reference_changed},
}
