### ISSUE TITLE
fix pytest log output

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#283]
After adding tenacity to retry async test failures if a test fails we get an enormously long traceback that consists mainly of the elasticsearch `GET` requests. It makes it impossible to find the root cause of the error or to check it for multiple tests. We should improve it. One option might be suppressing the `elasticsearch` logger, but ideally, we should suppress only `GET` requests to ES that are used for test assertion.

**Comment by drjova** [comment]
@MJedr can we close this?
