### ISSUE TITLE
move workflow root table to hep

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#3]
Move the https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/models.py#L102-L129, create a REST API for it and replace the next calls to this table with API calls to hep

**Comment by nooraangelva** [comment]
**TECH NOTES**

- Move [root table](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/models.py#L102-L129) to [here](https://github.com/inspirehep/inspirehep/blob/12384994db179c2d11412078f04eb0f2c4d4751f/backend/inspirehep/submissions/views.py)
- Create a REST API [here]() to call the root table from hep **still figuring out where and trying to find a reference REST API**
- replace [next table calls](https://github.com/inspirehep/inspire-next/search?q=WorkflowsRecordSources) with API calls to hep

**Comment by drjova** [comment]
@nooraangelva a reference to a REST API is here https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/views.py#L370-L426. Also I would move the root table to https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/models.py

**Comment by drjova** [comment]
- [ ] merge next
- [ ] stamp the migration (hep)
- [ ] test
