### ISSUE TITLE
search in private notes in holdingpen

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#30]
It would be useful to be able to search in private notes in the holdingpen, so we should add `_private_notes.value` to the mappings for `holdingpen-hep`.

**Comment by MJedr** [comment]
* remap & reindex HP:
```
inspirehep index create -b inspirehep/modules/workflows/mappings/v7/holdingpen/hep.json --force <index name>
# Change alias holdingpen and holdingpen-hep to point to the new index
inspirehep holdingpen reindex --data-type hep
```

**Comment by drjova** [comment]
Works as expected https://inspirehep.net/holdingpen/list?page=1&size=10&q=metadata._private_notes.value:%22DOKIFILE:IEEENuclSciSympConfRec_C9667777%22
