### ISSUE TITLE
exact match on persistent identifiers sometimes fails

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#309]
Florian reports in https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/matcher.20has.20problems.20with.20theses/near/357820639

> Another issue in this context which I thought was already solved. Or did we only created a ticket once and that's it?
The matcher should not only use arXiv and DOI but also HDL and URN to find direct matches:
https://inspirehep.net/holdingpen/5533750
https://inspirehep.net/literature/2658298

Matching on persistent identifiers has been implemented so in principle this should work. We need to understand why this failed and fix it.

**Comment by MJedr** [comment]
I couldn't reproduce it on given example:

```
In [17]: obj = workflow_object_class.get(5533750)

In [18]: exact_match(obj, None)
[2023-07-27 11:44:15,987: WARNING/MainProcess] py.warnings: /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Out[18]: True

In [19]: obj.extra_data['matches']
Out[19]: {u'exact': [2659599, 2658298], u'fuzzy': []}
```
