### ISSUE TITLE
Don't treat stub records as curated for the purpose of user claiming

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#31]
When a user claims records from a different profile, we check whether the papers are already claimed and if so don't allow automatic claiming but generate a curator ticket. When the claimed paper is part of a stub record (automatically created), we shouldn't do that but still allow automatic claiming.

**Comment by MJedr** [comment]
**TECH NOTES**
* add a function which will get literature author (the claimed one) from literature record and will check if it's stub one (so should have `'stub': True`.
* add a function that will get the papers for lit recids (`claimed_literature_recids`), will check if the claimed author is stub (using the other function for the first bullet) and will return the list of recids that actually can be claimed.
* call this function [here](https://github.com/inspirehep/inspirehep/blob/da9b08ba20eb0ee2e2a3e7d90dbb8ae69b44fede/backend/inspirehep/assign/views.py#L121) and if there are some recids that can be claimed add them to `literature_recids`. 
* update `claimed_literature_recids` by making a set diff between `claimed_literature_recids` and those that actually can be assigned. 
* update the returned json [here](https://github.com/inspirehep/inspirehep/blob/da9b08ba20eb0ee2e2a3e7d90dbb8ae69b44fede/backend/inspirehep/assign/views.py#L129) by adding a key `'created_rt_ticket': True`
* in author assign different profile action [here](https://github.com/inspirehep/inspirehep/blob/da9b08ba20eb0ee2e2a3e7d90dbb8ae69b44fede/ui/src/actions/authors.js#L175) check the response - if there is no `created_rt_ticket` inside of the response call `assignSuccessDifferentProfileUnclaimedPapers`
