### ISSUE TITLE
improve fuzzy matcher when one side has no authors at all

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#314]
many LHC papers, which didn't have authors on their arXiv preprints due to the Ukraine war and related authorship issues, are currently getting published. Because the arXiv record has no authors but the publisher update does, the fuzzy matcher fails validation due to https://github.com/inspirehep/inspire-matcher/blob/67e8f44121f1a8a8a7d05c20cde978d0462cc00b/inspire_matcher/utils.py#L52-L53. That should be changed so if one side has no authors, the validator treats it as a perfect author match, instead of a terrible author match.

**Comment by drjova** [comment]
@michamos  I'm testing this feature, even in the case that one side has no authors the score is `0` from the comparator, or am I missing something?
