### ISSUE TITLE
exact match fails for a thesis

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#316]
See https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/matcher.20has.20problems.20with.20theses/near/357820639

**Comment by MJedr** [comment]
actually, I tried exact_match for the given example, it's returning correct results:
```
In [3]: from inspirehep.modules.workflows.tasks.matching import *

In [4]: exact_match(obj, None)
Out[4]: True

In [5]: obj.extra_data['matches']
Out[5]: {u'exact': [2658298, 2659599], u'fuzzy': []}

In [6]: obj.id
Out[6]: 5533750
```

I am closing the issue, we can reopen it if the situation will repeat.
