### ISSUE TITLE
change wording on top `claim` menu entries

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#32]
Instead of `this is my paper`/`this is not my paper`, the `claim` menu at the top should have entries that are plural: `these are my papers`/`these are not my papers` as they affect potentially several records.

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES:
- in https://github.com/inspirehep/inspirehep/blob/f30ad22e60c3e68d29787382a4527f44464d228c/ui/src/authors/components/AssignAction.jsx#L57 change _this is my paper/this is not my paper_ dropdown items to plural if more than one publication is selected.

**Comment by drjova** [comment]
@michamos is the plural always displayed or depends on the selection size?

**Comment by MJedr** [comment]
change also there
https://github.com/inspirehep/inspirehep/blob/f30ad22e60c3e68d29787382a4527f44464d228c/ui/src/authors/components/AssignOwnProfileAction.jsx#L57-L62
