### ISSUE TITLE
add `edit` button for experiments

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#328]
We don't have an `edit` button in the `experiments` collection. We should add it (for curators) like for other collections.

**Comment by drjova** [comment]
The edit button is missing from the brief view

**Comment by michamos** [comment]
also the detailed view

**Comment by drjova** [comment]
> also the detailed view

![Screenshot 2023-06-05 at 09 17 14](https://github.com/cern-sis/issues-inspire/assets/4287772/9aa51c60-b619-4e8e-ae42-1697995af25f)

Hmm, do I miss something?

**Comment by michamos** [comment]
huh, I could have sworn they were missing there too. I don't know how I missed that 😅

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:** 

1. In https://github.com/inspirehep/inspirehep/blob/2ea2747dfd1c2c18913be17a746f88926245a9f3/ui/src/experiments/components/ExperimentItem.jsx in leftActions add <EditRecordAction /> component
