### ISSUE TITLE
fix small bugs in reference self-curation UI

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#342]
there are two small UI issues remaining with reference self-curation:
* the window scrolls back to the top after successfully editing a reference and refreshing the reference list
* the search state in the drawer is not cleared after a successful edit, so subsequently editing a different reference still displays the search results from the previous one when the drawer opens.

**Comment by karolina-siemieniuk-morawska** [comment]
+ make references stay on the same page after reference update (now after refresh it goes back to page 1)
