### ISSUE TITLE
parse ORCIDs from APS

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#343]
APS now puts ORCIDs into their XML files. We should add their handling to the parser in hepcrawl so we add these ORCIDs to our records.

**Comment by michamos** [comment]
Example: https://inspirehep.net/files/001ed07a15db98d367c548835954478e has
```xml
<contrib contrib-type="author">
        <contrib-id authenticated="true" contrib-id-type="orcid">
                https://orcid.org/0000-0003-1813-2645
        </contrib-id>
        <name>
                <surname>Hasenfratz</surname>
                <given-names>Anna</given-names>
        </name>
        <xref ref-type="aff" rid="a1">
                <sup>1</sup>
        </xref>
        <xref ref-type="author-notes" rid="n1">
                <sup>,*</sup>
        </xref>
</contrib>
```

**Comment by MJedr** [comment]
**Tech notes**
In jats parser add a method to extract id from author node and add it [there](https://github.com/inspirehep/hepcrawl/blob/2fbdc830ffa4b861a2af34ad3b916549270dc92e/hepcrawl/parsers/jats.py#L522)

**Comment by drjova** [comment]
@MJedr can we close this one?

**Comment by michamos** [comment]
It's working: https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=j%20phys.rev.%2A%20and%20authors.ids.schema%3AORCID

**Comment by michamos** [comment]
When was this deployed? https://inspirehep.net/holdingpen/5828266 from yesterday doesn't have ORCIDs, although they are present in the XML file.

**Comment by drjova** [comment]
@michamos my bad, it's not deployed. Sorry for the false alarm
