### ISSUE TITLE
Unsubscribed users can't resubscribe to mailtrain

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#360]
A user is reporting that they can 't resubscribe to the jobs mailing list after unsubscribing https://rt.inspirehep.net/Ticket/Display.html?id=1367282. I've investigated by subscribing and unsubscribing and it indeed looks like once you unsubscribe, you can't resubscribe.

**Comment by drjova** [comment]
When an email is unsubscibed and try to subscribe again using this link:
![Screenshot 2024-09-09 at 13 31 32](https://github.com/user-attachments/assets/3ad6b6b9-cf7d-4994-952c-711d767071c7)
it replies with 200 but actually the email still remains as unsubscribed https://lists.inspirehep.net/lists/view/3.

We have to check the API documentation of the mail train and probably change the payload [here](https://github.com/inspirehep/inspirehep/blob/df7bf823f22d25ace6837afe74b80cf8083ddb22/backend/inspirehep/mailing/providers/mailtrain.py#L26-L32)
