### ISSUE TITLE
merger produce invalid metadata

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#37]
Merger produces not valid metadata, usually the issue is with the following fields: 
* `figures` 
* `persistent_identifiers`
* `copyright`
Which instead of `[]` are empty `{}` and prevents editor to open.

**Comment by MJedr** [comment]
example error 
```
Error: "copyright" in {} is specified as "array" by schema but it is not an array in json
```
https://inspirehep.net/editor/holdingpen/4291127
