### ISSUE TITLE
add format for CV HTML to API

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#38]
From https://rt.inspirehep.net/Ticket/Display.html?id=1208929

We expose the CV HTML format in the citation dropdown, but we don't document it in the API, and it's only available through content negotiation, it can't be requested through a `format` request arg. We should define a format name for it and document it.

**Comment by nooraangelva** [comment]
**[WIP] TECH NOTES**

- Add [here](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/backend/inspirehep/tools/utils.py#L16) CV HTML format
-
