### ISSUE TITLE
Improve cypress local setup

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#393]
Running cypress locally is a nightmare, commands we use don't work anymore. That should be improved. Some of the issues are:
- wrong image tag in cypress docker-compose (should be cypress/included:13)
- wrong script name in `cypress-tests.sh`, maybe we should make it customisable to pass if we want to run chrome/firefox when executing script
- on mac m1 chrome and firefox don't work with current test setup

**Comment by karolina-siemieniuk-morawska** [comment]
**Tech notes:**

1. In [docker-compose.cypress.dev.yml ](docker-compose.cypress.dev.yml) and [docker-compose.cypress.yml](https://github.com/inspirehep/inspirehep/blob/d75be8588e4a347d91c920a4bc2fb03a877d9099/e2e/docker-compose.cypress.yml) change image version to `cypress/included:13`
2. In [cypress-test.sh](https://github.com/inspirehep/inspirehep/blob/a7d9b5cf1e566decc539a0c1224e36d8b95fa274/cypress-tests.sh) change the last line to correct file names (`cypress-tests-run-chrome` and `cypress-tests-run-firefox`)
3. Fix failing tests (author and literature submission - locally returns 50?, conference edit - missing legacy_ICN field, chrome - out of memory fail)
4. Test thoroughly and fix flaky test cases
