### ISSUE TITLE
require `titles.title` in conferences

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#404]
the `titles` field in conferences is not required, but the UI assumes it is. In practice it's always present, so we should change the schema to require it.

**Comment by drjova** [comment]
TECHNOTES:

1. Add `titles` as a required field [here](https://github.com/inspirehep/inspire-schemas/blob/09a3abd41ad934d9557a2b9c41e909d3d9a14520/inspire_schemas/records/conferences.yml#L309)
2. Update the tests to cover this case.


ACCEPTANCE:
- When the user submits a conference without a title it should fail with validation error.
- When the developer create or update a conference via the API and doesn't have title it should fail with validation error.
- When an applicaation create or update a conference via the RESTAPI and doesn't have title it should fail with validation error.

**Comment by drjova** [comment]
Get the control_number of the conferences without a title, use ES query.
