### ISSUE TITLE
Jobs facets should do `OR`, not `AND`

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#407]
Since https://github.com/inspirehep/inspirehep/pull/3069, it seems that the field of interest jobs facet has changed behavior. It now performs `AND` instead of `OR`.

For example, selecting both `hep-th` and `math` should return all records that have either `hep-th` or `math`, instead of only those having both.

**Comment by PascalEgn** [comment]
What is the intended behavior with the "Other" category. Should it also be treated as a normal category, so if for example `hep-th`, `math` and `Other` is selected it should show the results from all 3 categories?

**Comment by michamos** [comment]
Yes, always `OR`, `Other` is just another category from the user's
perspective
