### ISSUE TITLE
arxiv completeness script

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#418]
We could move the check into a bot

- [ ] move the check into a bot similar to https://github.com/cern-sis/errbot-retromaster so it can:

1. run everyday as a cron
2. run it on demand by passing the dates, for example !arxiv-completeness --from --to (by default today)

**Comment by MJedr** [comment]
**Tech notes** 
* On next (or hep) add arxiv completness check script and an endpoint that will call it. The tricky part is that it has to call ES (not OS) to parse holdingpen, so it's better to put it on next.
* Add an errbot plugin that will hit this endpoint.
