### ISSUE TITLE
Add grayed out claim button for non logged-in users

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#42]
When a user is not logged in, we should display a grayed out `claim` button at the top of profiles and on papers in the profile with the message on hover: `Login to claim your papers`. Similarly, when a user is logged in but doesn't have a profile, the button should be grayed out.

**Comment by karolina-siemieniuk-morawska** [comment]
**Tech Notes:**

- In _inspirehep/ui/src/authors/components_ catalog create new component DisabledClaimButton with grayed out claim button and 'Login to claim your papers' tooltip
- Add the created component here: https://github.com/inspirehep/inspirehep/blob/8e4a328d349717d13d1f4512d5383f00a4436165/ui/src/literature/containers/LiteratureSearchContainer.jsx#L132-L133 with `assignNoProfileViewCondition`

**Comment by karolina-siemieniuk-morawska** [comment]
@michamos should the tooltip be the same in both cases? (logged out and no profile)

**Comment by michamos** [comment]
No, the tooltip is diffferent. When no profile, keep the current one, when not logged in `Login to claim your papers`.

**Comment by karolina-siemieniuk-morawska** [comment]
Tech Notes:

- In: https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/AssignNoProfileAction.jsx add loggedIn: state.user.get('loggedIn') property and change the tooltip content based on the prop value
- Make sure that the button's disabled style is grayed out

**Comment by drjova** [comment]
@karolina-siemieniuk-morawska for the first point we are using contexts https://github.com/inspirehep/inspirehep/blob/master/ui/src/literature/components/LiteratureItem.jsx#L67-L77 connecting the component will not work as expected
