### ISSUE TITLE
wrong data after merge?

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#424]
There seems to be an issue with the merger and/or record editor, see https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/merging.20records/near/405125605. This is blocked by #423 that prevents us from having details about the error.

**Comment by karolina-siemieniuk-morawska** [comment]
@michamos I don't have access to linked chat, could you please add a better explanation of the issue to the task description?

**Comment by michamos** [comment]
Now #423 is fixed I managed to get a sentry event: https://sentry.siscern.org/inspire/record-editor/issues/321083/?query=is%3Aunresolved
