### ISSUE TITLE
don't strip `authors.ids` from search API

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#426]
Heath reports in https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/API.3A.20ORCID.20does.20show.20fir.20first.20author.20in.20.22authors.22.20element/near/406175822 that the [search API response for a given record](https://inspirehep.net/api/literature?sort=mostrecent&size=100&page=1&q=recid%3A2730489) doesn't contain `authors.ids` while the underlying record does: https://inspirehep.net/api/literature/2730489.

**Comment by drjova** [comment]
We have to check https://github.com/inspirehep/inspirehep/blob/3619b73dc7b84e6a749f80b7b66dd79a0697849a/backend/inspirehep/records/marshmallow/literature/common/author.py#L62-L82

**Comment by PascalEgn** [comment]
Can't reproduce the Issue as [search API response for a given record](https://inspirehep.net/api/literature?sort=mostrecent&size=100&page=1&q=recid%3A2730489) returns an empty search. 

@michamos do you have another example to reproduce the problem?

**Comment by michamos** [comment]
@PascalEgn not empty for me, could you try again?

**Comment by PascalEgn** [comment]
Tech notes:

Problem only seems to occur with records that are not in the INSPIRE Literature collection.

Add unit tests to further understand the behavior and debug [this function](https://github.com/inspirehep/inspirehep/blob/3619b73dc7b84e6a749f80b7b66dd79a0697849a/backend/inspirehep/records/marshmallow/literature/common/author.py#L62-L82).

**Comment by drjova** [comment]
@michamos deployed
