### ISSUE TITLE
add author.xml support to record editor

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#427]
in the record editor, it is possible to populate authors either by inputting a URL or a free text. It would be useful to extend this so author.xml is supported too. This likely requires moving the [author.xml parsing](https://github.com/inspirehep/inspire-next/blob/9c6db67c8b0b12435f92fd4c9093d9e02082f636/inspirehep/modules/workflows/tasks/arxiv.py#L284) to hep.

When a curator copy/pastes an author.xml string to the textarea and clicks on `extract`, the author.xml should be parsed and the affiliations should be linked using https://github.com/inspirehep/inspirehep/blob/b3cd531aa52af18e2883be3674ddbf1d3f2c322a/backend/inspirehep/curation/api.py#L111 or https://github.com/inspirehep/inspirehep/blob/b3cd531aa52af18e2883be3674ddbf1d3f2c322a/backend/inspirehep/curation/views.py#L118-L133.

In addition, the message in the editor textarea should be changed from `Text or URL` to `Text, author.xml or URL`.

**Comment by drjova** [comment]
TECH NOTES

**backend**
* move author.xml parsing to inspire-schemas (builder it's there too)
* create an endpoint in https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/curation/views.py for admin or admin roles

**frontend**
todo

**Comment by drjova** [comment]
@michamos could you please give me an authorxml example with its expected output?

**Comment by michamos** [comment]
It's exactly the same logic as currently implemented on next, you can reuse
the test cases there.

**Comment by drjova** [comment]
> It's exactly the same logic as currently implemented on next, you can reuse the test cases there.

If we had, I wouldn't ask you. I can see only one [test](https://github.com/search?q=repo%3Ainspirehep%2Finspire-next%20collaborationauthorlist&type=code) with a full author XML, maybe I'm missing something. Anyway, I will work with it.

**Comment by michamos** [comment]
OK, I expected there to be an extensive test suite and thought there was some misunderstanding. This is surprising to me. The problem with author.xml files is that they're typically huge (thousands of authors), so I'm not sure what kind of test you want to have.

While you're working on this, there is a small improvement that could be made, [reported on Zulip](https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/author.2Exml/near/449066743).
```xml
<foaf:Person>
<foaf:name>Kentaro Miuchi</foaf:name>
<foaf:familyName>Miuchi</foaf:familyName>
<cal:authorNamePaper>K.~Miuchi</cal:authorNamePaper>
<cal:authorCollaboration collaborationid="c1"/>
<cal:authorAffiliations>
<cal:authorAffiliation organizationid="a24"/>
</cal:authorAffiliations>
</foaf:Person>
```
There is no `<foaf:givenName>`, so it should fall back to `<foaf:familyName>` instead (passing through `inspire_utils.name.normalize_name`), and the resulting name in the record should be `Miuchi, Kentaro`. Note that this is not a self contained example as it refers to an `organizationid` that is not defined here, but you can get the full XML file from https://arxiv.org/src/2403.14878.
