### ISSUE TITLE
Create account menu

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#43]
To make it easier for users to get to their profile, we want to create an `Account` menu to replace the current `Logout` button on the top-right. The menu has two entries, `My profile` and `Logout`. `My profile` is a link to the profile with the same ORCID as the currently logged in user. If the user doesn't have a profile, we gray out the `My profile` button and display on hover the same message as for claiming: https://github.com/inspirehep/inspirehep/blob/26ab34eac04bd3cf42541a2c7dd564c868f881b1/ui/src/authors/components/AssignNoProfileAction.jsx#L12-L13.

**Comment by karolina-siemieniuk-morawska** [comment]
Tech notes:

- In https://github.com/inspirehep/inspirehep/blob/23f6d3443e82e66b25db254e479313c6d1f45d33/ui/src/common/layouts/Header/HeaderMenu.jsx#L83-L91 replace logout button with <Menu.SubMenu> element containing two items: My profile and Logout. 
- In https://github.com/inspirehep/inspirehep/blob/master/ui/src/common/layouts/Header/HeaderMenuContainer.jsx add property orcidId: state.user.getIn(['data', 'orcid'])
- My Profile should be <Link> element with url to users' orcid profile 
- Logout should be <LinkLikeButton> element if property loggedIn === true, or <Link> element if user is logged out. 
- My profile button should have 'disabled' attribute and style if props loggedIn === false, with <Tooltip> (_There is no profile associated to your account. Please contact us at <a href="mailto:authors@inspirehep.net">authors@inspirehep.net</a>_).

**Comment by karolina-siemieniuk-morawska** [comment]
Clarification from Micha:

_When user not logged in, they get the current Login button, when logged in, they get the menu, with a greyed out entry if they have no profile._
