### ISSUE TITLE
display INSPIRE ID for authors that don't have an ORCID

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#431]
When an author doesn't have an ORCID but has an INSPIRE ID, we should display the latter on the author profile. The data comes from `ids.value` where `ids.schema` is `INSPIRE ID` and should be displayed under `Author identifier`.

Mockup for https://inspirehep.net/authors/1010044: 

![Image](https://github.com/cern-sis/issues-inspire/assets/2895793/3da16531-3885-41cc-8eaf-15d3d8abb749)

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**

1. In `/authors`, create new component `InspireIdentifier.tsx` similar to `AuthorBAI.tsx` and pass Inspire id as props
2. In [DetailPageContainer.tsx](https://github.com/inspirehep/inspirehep/blob/4292a9a8a700fa7be3c7307d6a079c9eb5941cbf/ui/src/authors/containers/DetailPageContainer/DetailPageContainer.tsx) create logic to retrieve Inspire id from `ids` field and return it if there is no `userOrcid` prop present
3. [Here](https://github.com/inspirehep/inspirehep/blob/4292a9a8a700fa7be3c7307d6a079c9eb5941cbf/ui/src/authors/containers/DetailPageContainer/DetailPageContainer.tsx#L241-L242) add the `InspireIdentifier.tsx` component when above conditions are met
