### ISSUE TITLE
remove inspire-next dependency from inspirehep

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#437]
Remove inspire-next from the services and tests. That will need to mock e2e tests with inspire-next responses (i.e. forms)

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**
1. Remove inspire-next from [docker-compose.services.yml](https://github.com/inspirehep/inspirehep/blob/9d00330a9ed9f580e8a7344464e356a5dcf8d7b1/docker-compose.services.yml)
2. Remove next-web and next-worker container form [docker-compose.yml](https://github.com/inspirehep/inspirehep/blob/762512e8a54c5a9cf834d7e396b67bb119423719/docker-compose.yml)
3. Mock responses for submissions of all collections in cypress tests
