### ISSUE TITLE
Display count of claimed records on success toast

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#44]
After claiming, the toast should display how many records are going to be claimed: instead of `All selected...`, `All [N] selected ...`.

**Comment by karolina-siemieniuk-morawska** [comment]
Tech notes:

- In: https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/assignNotification.jsx change the    assignSuccessDifferentProfileUnclaimedPapers function to display number of papers that are going to be claimed and make sure the assignSuccessOwnProfile is working correctly.

**Comment by MJedr** [comment]
Due #31 where we will probably reclassify some papers as possible to claim it might be necessary to sum the number of unclaimed and claimed to stub record and pass it to the `assignSuccessDifferentProfileUnclaimedPapers`

**Comment by karolina-siemieniuk-morawska** [comment]
Tech notes:

- In [assignNotification](https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/assignNotification.jsx#L43-L79) change following functions: assignSuccessOwnProfile , unassignSuccessOwnProfile , assignSuccessDifferentProfileUnclaimedPapers to display `numberOfUnclaimedPapers` that are selected for claiming
