### ISSUE TITLE
link to conference contributions from conference detailed view

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#443]
On conference search pages, we link to all related conference papers with the `N contributions` link on the bottom-right of the card. This link is not available on the conference detailed view, as the same contributions are displayed underneath as an embedded search. 

However, it's sometimes useful to perform an external search in case you want to refine the query, which is not possible in the embedded search. So we should add the link also to the detailed view.

Example: [search with link](https://inspirehep.net/conferences?sort=dateasc&size=25&page=1&start_date=all&q=control_number%3A1812650), [detailed record without](https://inspirehep.net/conferences/1812650).

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES:

1. Extract contribution link from [ConferenceItem.jsx](https://github.com/inspirehep/inspirehep/blob/a32488576e8b4a208554fc096d1d4dc607d27539/ui/src/conferences/components/ConferenceItem.jsx#L52-L66) to separate component `ConferenceContributionLink.tsx`
2. Replace lines highlighted above in `ConferenceItem.jsx` with new component
3. Add new component as `rightActions` prop to `<ContentBox />` in [DetailPageContainer.jsx](https://github.com/inspirehep/inspirehep/blob/4292a9a8a700fa7be3c7307d6a079c9eb5941cbf/ui/src/conferences/containers/DetailPageContainer.jsx)
