### ISSUE TITLE
book chapters (with `publication_info.parent_record` field) are incorrectly displayed

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#445]
A user [reports](https://cern.service-now.com/nav_to.do?uri=%2Fu_request_fulfillment.do%3Fsys_id%3Defd00aa3972b75108a6b34ae2153af22%26sysparm_view%3Dtabs_new%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull) the following issue.

Consider the following example:

  recid:2610328
  On the origin of stellar energy
  Lev Davidovich Landau
  1937
  2 pages
  Part of Собрание трудов [Sobranie trudov]. Vol. 1, 333-334
  Published in: Nature 141 (1938) 3564, 333-334, Compt.Rend.Acad.Sci.URSS 17 (1937) 6, 305-306, Dokl.Akad.Nauk SSSR 17 (1937) 6, 301-302
  Published: Feb 19, 1938 and Published: 1937 and Published: 1965 in Oxford by Pergamon Press and Published: 1969 in Moscow by Наука [Nauka] 
  DOI: 10.1038/141333b0, 10.1016/b978-0-08-010586-4.50032-8

The string:

  {"year":1965,"page_end":"186","page_start":"185","parent_isbn":"9780080105864","parent_record":{"$ref":"https://inspirehep.net/api/literature/2610294"},"curated_relation":true},
  {"year":1969,"page_end":"226","page_start":"224","parent_record":{"$ref":"https://inspirehep.net/api/literature/2730766"},"curated_relation":true}

contained in:

  https://inspirehep.net/api/literature/2610328

is not correctly dislayed in:

  https://inspirehep.net/literature/2610328

The following 2 errors occur: The piece

    {"year":1965,"page_end":"186","page_start":"185","parent_isbn":"9780080105864","parent_record":{"$ref":"https://inspirehep.net/api/literature/2610294"},"curated_relation":true},

is not displayed at all in https://inspirehep.net/literature/2610328.

The second piece

    {"year":1969,"page_end":"226","page_start":"224","parent_record":{"$ref":"https://inspirehep.net/api/literature/2730766"},"curated_relation":true}

is displayed with the wrong page numbers (333-334 instead of 224-226; the page numbers 333-334 belong to the Nature
entry of the record).

This should be remedied.

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**

 **Backend:**
1. `linked_book` field should be renamed to `linked_books` and include all the publications that have` parent_record` field 
2. Apart from `title` and `source` fields it should also have `page_start` and `page_end` field

**UI**
1. Refactor [ParentRecordInfo.jsx](https://github.com/inspirehep/inspirehep/blob/5b1c0d4f14f8a677cf3203888635c302a1b50b01/ui/src/literature/components/ParentRecordInfo.jsx) component to display all linked books and correct pages
