### ISSUE TITLE
Add claim button to literature detailed view

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#45]
We want to make it easier for users to claim papers that are not in their profile. We need to add a claim button to the Literature detailed view. This button is grayed out when not logged in or there is no profile for the account, with a `Move to my profile` dropdown when logged in and there is a profile for the account.

When clicking on `Move to my profile`, there are two cases:
* there is a single name in the paper that matches a name of the current author (first by last name only, then with initials, then by full name): in that case, assign that paper author to the current author record
* there is no name that matches or the match is ambiguous: open a sidebar where the user can pick which name he wants to claim (UI to be defined more precisely).

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES:
1. Create displayClaimingButton function with the below logic, which will return correct component and place it [here](https://github.com/inspirehep/inspirehep/blob/0c78b52dfb424fa2b5dbb1776286e087adaab717/ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx#L118 )
  - For logged out user, display `[ClaimingDisabledButton](https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/ClaimingDisabledButton.jsx)` 
  - For user with no profile, display `[AssignNoProfileAction](https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/AssignNoProfileAction.jsx)`
  - If there is a single name in the paper that matches a name of the current author, create AssignLiteratureOwnItem and AssignLiteratureItemOwnContainer components with the logic of similar to [AssignOwnProfileAction] (https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/AssignOwnProfileAction.jsx) 
  - if there is no name that matches or the match is ambiguous create AssignLiteratureDifferentItem and AssignLiteratureItemDifferentContainer components that will open the sidebar with author's name selection

**Comment by michamos** [comment]
yes, the idea is to have a way for users to select a name in case none match (or several do). Not sure I understand the question, let's discuss it further.

**Comment by MJedr** [comment]
tech notes (backend):
* modify [this](https://github.com/inspirehep/inspirehep/blob/0c78b52dfb424fa2b5dbb1776286e087adaab717/backend/inspirehep/assign/utils.py#L67-L75) to check the name compatibility for:
1. last name only, 
2. last name with initials
3. full name
There should be only one match, otherwise return False from the function.
* From frontend we need to get with the request name that an author wants to claim (along with papers ids etc.). Modify [rt ticket](https://github.com/inspirehep/inspirehep/blob/0c78b52dfb424fa2b5dbb1776286e087adaab717/backend/inspirehep/assign/tasks.py#L242) to put the name that author wants to claim [here](https://github.com/inspirehep/inspirehep/blob/0c78b52dfb424fa2b5dbb1776286e087adaab717/backend/inspirehep/assign/tasks.py#L269) and cleanup the function.

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES:

Create displayClaimingButton function that will return correct component according to instructions below👇 and place it [here](https://github.com/inspirehep/inspirehep/blob/0c78b52dfb424fa2b5dbb1776286e087adaab717/ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx#L118)
For logged out user, display [ClaimingDisabledButton](https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/ClaimingDisabledButton.jsx)
For user with no profile, display [AssignNoProfileAction](https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/AssignNoProfileAction.jsx)
For logged in user with profile create AssignLiteratureOwnItem button similar to [AssignOwnProfileAction](https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/AssignOwnProfileAction.jsx) with Move to my profile dropdown. If there is unambiguous match it should assign that paper author to the current author record. If there is no unambiguous match or no match at all, it should open the sidebar.
Create sidebar/drawer similar to what is used for assigning conference on the literature search view. It should display the list of authors present on the paper (taken from metadata), with the possibility to select the name the user declares as his. On name select it should create a rt_ticket
