### ISSUE TITLE
extract ORCID and emails in authorlist exctraction tool

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#47]
The record editor allows to extract author info (author names and raw affiliations) from a specially formatted author list. This ends up using https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/editor/authorlist_utils.py.

We should also add support for extracting ORCIDs and email addresses from the raw affiliation field. That is, if there is some text that looks like an email address or an ORCID in that field, it should end up in `authors.ids` instead of `authors.raw_affiliations`.

Example:
```
Frank Castle1

1 frank.castle@example.com 0000-0003-1134-6827 Example Universtity of Stuff
```

**Comment by MJedr** [comment]
TECH NOTES:
1. Add a regex for checking if a word is an email or an ORCID
2. Create variables for email and orcid [here](https://github.com/inspirehep/inspirehep/blob/0c78b52dfb424fa2b5dbb1776286e087adaab717/backend/inspirehep/editor/authorlist_utils.py#L112-L114) and then check if processed word matches any of those regexes in [this else block](https://github.com/inspirehep/inspirehep/blob/0c78b52dfb424fa2b5dbb1776286e087adaab717/backend/inspirehep/editor/authorlist_utils.py#L125-L144) and if yes assign it to the corresponding variable

**Comment by MJedr** [comment]
@michamos are there any other possibilities/test cases than the one you provided?

**Comment by nooraangelva** [comment]
Should the emails go to ```authors.emails``` rather? @michamos

**Comment by michamos** [comment]
Indeed, emails should go to `authors.emails`.
