### ISSUE TITLE
Redirect data to new backoffice - add feature flag

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#482]
TECH NOTES:
  * Create an Bearer token in backfofifce for creating workflows
  * Update k8s with the token in hep `BACKOFFICE_BEARER_TOKEN`
   * Refactor [this](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/views.py#L82) function to accept a url and token a parameter instead of having only next hardcoded
   * Refactor the code if needed to use the new function
 * Add a feature flag [here (https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/views.py#L194) `FEATURE_FLAG_ENABLE_SEND_TO_BACKOFFICE` and send also to the new backoffice (using the function).

**Comment by drjova** [comment]
Test in QA that submissions are going to backoffice as well (i.e. FEATURE FLAG, TOKEN etc)
