### ISSUE TITLE
add curation actions

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#483]
Configure curation actions from backoffice, the curators/admins, should be able to do the following actions:

*  'Approve'
* 'Reject' 
*  restart
* skip to step (by default next)
* restart current
* restart with params

We already have the airflow DAGs, we need to have configure the airflow API and document how each one is working.

**Comment by DonHaul** [comment]
@drjova 
This is dependent on:
https://github.com/inspirehep/workflows/pull/2/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9
I have made a few minor changes to the airflow repo so that it can works as intended

**Comment by DonHaul** [comment]
Another previous step must be implemented which is to trigger workflows in airflow through the backoffice.
An initial version has been implemented in https://github.com/DonHaul/backoffice/tree/submissions .
Needs to be rebased and adapted

**Comment by DonHaul** [comment]
https://github.com/inspirehep/backoffice/pull/45 first step, it: connects to airflow and triggers dags regarding:
- author creation
- author approval
- author rejection

**Comment by DonHaul** [comment]
In summary there's 3 new endpoints:

- POST `/api/workflows/authors` - to create an author. it replaces the previous /api/workflows, receives the same payload
- POST `/api/workflows/authors/<id>/resolve` receives:
```
{
  "value": "accept",  #or "reject"
  "create_ticket": true # or false
}
```
- POST `/api/workflows/authors/<id>/restart` receives:
```
{
  "restart_current_task" : true # if not specified defaults to false
  "params" : {dictionary with new params} # this was requested in user action buts its not yet specified what this params are, if not specified, a full restart is done
}
```
also it can simply have no payload, and in this case a full restart occurs
