### ISSUE TITLE
automatically close curation tickets when the `curated` flag is set

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#486]
When curators finish curating a record, they set the `curated` flag and also close the associated curation tickets. Unfortunately, sometimes they forget to close tickets, so the ticket remains open, incorrectly reflecting the state of the record. We should have a mechanism to automatically close curation tickets (not all tickets, only those in specific functional categories/queues) either when saving from the editor, or periodically at a later stage.

**Comment by drjova** [comment]
Double check if the curated flag is saved on "Save" or on status change with a separate API call.

**Comment by drjova** [comment]
@michamos could you please specify the queues/categories

**Comment by michamos** [comment]
Functional categories are `arXiv curation` and `Publisher curation`.

**Comment by drjova** [comment]
TECH NOTES:

* If there is `curated:  true` then make a request to close associate tickets for the following functional categories:
  * arXiv curation
  * Publisher curation
