### ISSUE TITLE
add GROBID author extraction from PDF to editor

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#49]
currently, we can extract author information in the editor by inputting specially formatted text in the textbox, which ends up calling https://github.com/inspirehep/inspirehep/blob/da9b08ba20eb0ee2e2a3e7d90dbb8ae69b44fede/backend/inspirehep/editor/views.py#L337-L345. We should add an alternative option to extract this information from PDF, similarly to what we do with refextract (either calling `/api/editor/refextract/url` or `/api/editor/refextract/text`). The extraction from PDF would use the same conversion from GROBID as in the workflows (https://github.com/inspirehep/inspire-next/blob/5075658ffffaaa704c320941a9cfaf79df35f167/inspirehep/modules/workflows/utils/grobid_authors_parser.py, note that the merging logic we use in the workflows is not needed), then call the affiliation normalization as in #48.

**Comment by MJedr** [comment]
TECH NOTES:
1. Add affiliation normalisation function to hep (do we want to deduplicate the code somehow or we don't care about the code on next? @drjova).
2. Add an endpoint in editor views which will call GROBID service. It should do the same thing as the workflow task here https://github.com/inspirehep/inspire-next/blob/9b42273a980e24a7f47730be716e65ab7f73e213/inspirehep/modules/workflows/tasks/actions.py#L852-L890, including grobid response parsing.
3. Call affiliation normalisation after that.
4.

**Comment by MJedr** [comment]
@drjova it seems possible but might require restructuring a bit the functionality since we use record search classes there
