### ISSUE TITLE
Add Journal collection to hep

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#5]
# Create a Journal collection ui
## Search
Example for https://inspirehep.net/api/journals/1213103
![Screenshot 2022-06-17 at 12-03-48 Experiments Search - INSPIRE](https://user-images.githubusercontent.com/2895793/174276935-3b8e99a6-4415-483a-88f9-8c54e1d948d7.png)
* clickable title: `short_title`
* in parentheses `publisher` (separated by commas when several)
* next line `journal_title`
* display `urls` as `links` button like for other collections and `edit` button for curators that opens the record editor (*not displayed on mockup*)

## Detailed view
![Screenshot 2022-06-17 at 14-03-43 CERN-LHC-ATLAS - INSPIRE](https://user-images.githubusercontent.com/2895793/174294688-a5bc4a34-0b71-4fa7-9895-3e69db26f852.png)
Similar to search, with the following changes:
* next to the full title, a button saying `Show other names ({number})`, clicking on it will open a popup with the list of `title_variants` (one per line)
* public notes under the journal title: `public_notes`
* An `Articles published in {short_title}` link to a Literature search for this journal record
* An embedded search for the same underneath (**optional, if not too much work**) instead of the link with the number of papers

**Comment by drjova** [comment]
@michamos could you please have a look?

**Comment by michamos** [comment]
@drjova done, let me know if it's clear, there are a few things that need discussion

**Comment by drjova** [comment]
@drjova thank you, what do you need we need to discuss?

**Comment by michamos** [comment]
how much effort it is to index the paper count and do the embedded search. We can postpone it if needed.

**Comment by drjova** [comment]
* Indexing the count is pretty easy just a function in the ES serializer
* Embedded search we already have the component, we have to add some internals first

Do you mind do it in 2 steps? first we finish with the initial setup and then add the embedded search?

**Comment by michamos** [comment]
> * Indexing the count is pretty easy just a function in the ES serializer

I was afraid it would require a new join table like for references or authors of papers. If that's not needed that's great news.

> Do you mind do it in 2 steps? first we finish with the initial setup and then add the embedded search?

No, that's good :+1:

**Comment by karolina-siemieniuk-morawska** [comment]
**Tech notes - journal submission**:

1. Create a form schema - fields to include are Title (should match short_title in form) and Journal Title (match journal_title in form)
2. Create following components - JournalForm, JournalSubmissionComponent 
3. Create a submission container
4. Define route for submission [here](https://github.com/inspirehep/inspirehep/blob/master/ui/src/common/routes.js)
5. Add route for submission [here](https://github.com/inspirehep/inspirehep/blob/master/ui/src/submissions/index.jsx)
6. Add the menu item [here](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/common/layouts/Header/HeaderMenu.jsx#L69) - visible only for curators (passing a prop from HeaderMenuContainer taken from state isCatalogerLoggedIn: isCataloger(state.user.getIn(['data', 'roles’])))

**Comment by karolina-siemieniuk-morawska** [comment]
**Tech notes - journal search page:**

- Write journals reducer to fetch journals from api and put them in store
- Create index file, and in it define routes for journal search page (<Route exact path={JOURNALS} component={JournalSearchPage} />)
- Create following components: JournalSearchPage, JournalItem
- Create JournalSearch container 
- JournalItem component should contain the following: clickable title: short_title, in parentheses publisher (separated by commas when several), next line: journal_title, display urls as links button like for other collections and edit button for curators that opens the record editor

**Comment by karolina-siemieniuk-morawska** [comment]
**Tech notes - journal detail page:**

- In index file, define a route for journal detail page (`< Route exact path={`${SEMINARS}/:id`} component={DetailPageContainer} / >`)
- Create `DetailPageContainer` (similar to other detail page containers, ie. seminars). Top `< ContentBox / >` component should contain similar info to `JournalItem`, except next to the full title, there should be a button saying _Show other names ({number})_, when clicking on it will open a popup with the list of `title_variants` (one per line), display public notes (`public_notes`) under the journal title,  a link (`Articles published in {short_title}`)
- The link should lead to Literature Search page with the standard query plus journal id (ie. `/literature?sort=mostrecent&size=25&page=1journal={id}`, make sure it's possible to put journals in query)

---

- Below `ContentBox` there should appear `<LiteratureSearchConteiner />` with the baseQuery prop set to the same value as query

**Comment by MJedr** [comment]
**backend for search & detail**
* add a marshmallow schemas for journals (ui and list schema, raw schema and admin are already there)
     * List schema (used for search) should contain `short_title`, `publisher`, `journal_title`, `urls`.
     * UI schema should contain `public_notes`, `short_title`, `publisher`, `journal_title`, `urls`.
     * In ES schema add a field `papers_count` which will contain the number of the papers assigned to that journal. 
* Add missing json serializers for journals (detail, list), [here](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/serializers/json/journals.py), also if there will be any difference between json response for curators and non-curators a conditional serialiser should be applied [like here](https://github.com/inspirehep/inspirehep/blob/2a3a9860bbffdd8813a19824e6a64f84859f30b0/backend/inspirehep/records/serializers/json/institutions.py#L23-L37). Add them [there](https://github.com/inspirehep/inspirehep/blob/2a3a9860bbffdd8813a19824e6a64f84859f30b0/backend/inspirehep/records/serializers/__init__.py).
* Update serializers in journals record config - [search](https://github.com/inspirehep/inspirehep/blob/2a3a9860bbffdd8813a19824e6a64f84859f30b0/backend/inspirehep/records/config.py#L293) and  [detail](https://github.com/inspirehep/inspirehep/blob/2a3a9860bbffdd8813a19824e6a64f84859f30b0/backend/inspirehep/records/config.py#L296-L297)  (add serializers for `"application/vnd+inspire.record.raw+json`)
