### ISSUE TITLE
Improve local setup

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#508]
Currently, because [postgres-backoffice](https://github.com/inspirehep/backoffice/blob/5250f56b13b98e81ba0a11753dd31b2ec6d8c773/docker-compose.yaml#L119) and [opensearch](https://github.com/inspirehep/backoffice/blob/5250f56b13b98e81ba0a11753dd31b2ec6d8c773/docker-compose.yaml#L148C3-L148C13) are not exposing their ports we cannot run the tests locally, only with a docker image.

**Comment by DonHaul** [comment]
@drjova is this just about exposing the ports to the local machine or does this also entail having a local setup independent of docker?

**Comment by drjova** [comment]
Yes, I think that would do
