### ISSUE TITLE
Add SENTRY to backoffice

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#512]
We have to enable SENTRY in the new `backoffice`, there is already [a project](https://sentry.siscern.org/inspire/backoffice/) we have to [configure](https://docs.sentry.io/platforms/python/integrations/django/) the DNS and make sure it works correctly.

**Notes:**
* Might be sentry SDK version issue that is not compatible with the Sentry version that we are running
* Logs (INFO) are not appearing in the PODS
* Scoap3 has sentry and it works

**Comment by DonHaul** [comment]
Indeed it was a problem with the sdk.
Tested severial `sentry-sdk` versions and the highest version it works with our current sentry installation is`1.19.1` .
On pypi there is `sentry-sdk 2.12.0` already in the next major version so we should consider upgrading out sentry server and all the dependencies whenever things calm down

**Comment by drjova** [comment]
For the moment we don't have plans updating sentry server, so let's keep this version for the moment
