### ISSUE TITLE
Decision action log

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#518]
We need to implement logging for curator decisions in the backoffice. When a curator makes a decision on an author submission (either "Accept" or "Reject")

This task is linked with #522, please handle them together

# Tech NOTES

## Database Schema:

Create a new table named Decision to store the following fields:

- created_at: DateTime field for when the decision was made.
- updated_at: DateTime field for when the decision was made.
- user_id: id field for the curator id
- workflow_id: uuid for the workflow identifier.
- action: enum field for the action taken, corresponding to the [resolution actions](https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/constants.py#L33)..

## Serializer:

Update the workflow serializer to include the Decision data. 

## Views
- On resolve store the decision here https://github.com/inspirehep/backoffice/blob/181b542c407bbe98e29c5d1b1bf1b4ae11e1f423/backoffice/backoffice/workflows/api/views.py#L159
- On workflows/authors  requestion we should return the decision as well:
```json
{
  "decision": "accept" | "reject" | "accept curate"
}

```

## UI
Display the decision in the UI

# NOTES:

- A Decision table is created and properly integrated into the database schema and run migrations on `dev`
- The workflow serializer is updated to include decision details.
- Curator actions are logged correctly with all required details.

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES (for UI):**

1. In [AuthorDetailPageContainer.tsx ](https://github.com/inspirehep/inspirehep/blob/3ec50ba958129b7a69116baac3c688415ea6e88c/ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx#L321-L374) when status is ```completed``` instead of displaying decision buttons, display decision.
