### ISSUE TITLE
SNOW ticket information

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#519]
We need to enhance our existing workflow model by including it in the serializer and adding an attribute for ticket_url.

- [Workflow Model](https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/models.py#L36) The model already exists in our codebase.

# TECH NOTES

- [x] Update the workflow serializer to Include the WorkflowTicket .
- [x] Add a dynamic attribute for ticket_url to the WorkflowTicket serializer.
- [x] The workflow author API should return additionally:
```js
{
    "tickets": [
        {
             “ticket”t_id": “”, 
             “ticket_url”: “”
        }
    ]
}
```

Example Serializer:

```python

class WorkflowTicketSerializer(serializers.ModelSerializer):
    class Meta:
        model = WorkflowTicket
        fields = ['workflow_id', 'ticket_id', 'ticket_type', 'ticket_url']

    def get_ticket_url(self, obj):
        # Assuming you have a method or a property to generate the URL for a ticket.
        return f"https://example.com/tickets/{obj.ticket_id}"


class WorkflowAuthorsSerializer(serializers.ModelSerializer):
    tickets = WorkflowTicketSerializer(many=True, read_only=True)
    
    class Meta:
        model = Workflow
        fields = ['id', 'workflow_type', 'data', 'status',  'is_update', '_created_at', '_updated_at', 'tickets']


```

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES (for UI part):**

1. In [AuthorDetailPageContainer.tsx ](https://github.com/inspirehep/inspirehep/blob/3ec50ba958129b7a69116baac3c688415ea6e88c/ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx#L404-L414) handle new data structure for SNow ticket.
