### ISSUE TITLE
Display Airflow link on Error

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#520]
When a workflow status is error, we need to display a link to the Airflow admin interface for the corresponding DAG to admin users. The dag_ids have the same IDs as the workflows.

# Tasks

- [x] Define how to generate a link to the Airflow admin interface given the workflow_id.
- [ ] Display a link in the UI when status: error

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES (for UI):**

1. In [AuthorDetailPageContainer.tsx ](https://github.com/inspirehep/inspirehep/blob/3ec50ba958129b7a69116baac3c688415ea6e88c/ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx) delete lines 171-176. Instead display hyperlink to Airflow.
2. In Error section delete display of error message and change it to the airflow  link with information that this is a link to the error details.

**Comment by DonHaul** [comment]
Could be Blocked by cern-sis/issues-inspire/issues/518
As to know, in which dag we are we nees access to which decision have or havent been done.

Alternatively we could just find the failing dag and return it with `find_failed_dag()`

**Comment by drjova** [comment]
A simple link `dagrun/list/?_flt_0_run_id=<PK>` would be enough for now
