### ISSUE TITLE
Restart workflow action doesn't work on author

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#523]
1. When the workflow is created manually through admin panel:
    - restart workflow works
    - restart current step fails with 500 error
    - when accepting/rejecting it goes to 'error' state with error ```Partial update for workflows is missing an argument ‘collection’```

2. When the workflow is created through author submission in Inspire:
    - restart workflow return 424 error no matter the payload (empty or params: {})
    - restart current step fails with 500 error

**Comment by DonHaul** [comment]
First Step to fixing 2.
https://github.com/inspirehep/inspirehep/pull/3210
