### ISSUE TITLE
Restart workflow action don't work

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#526]
Restart workflow always returns 502.

Request:
i.e. https://backoffice.dev.inspirebeta.net/api/workflows/authors/3bd4778b-96e4-474a-bbc7-ef0c231ef91d/restart/
payload: {} (empty object)

Response:
502
```
Unable to perform action
DAGRun with DAG ID: 'author_create_initialization_dag' and DAGRun ID: '3bd4778b-96e4-474a-bbc7-ef0c231ef91d' already exists
```

**Comment by karolina-siemieniuk-morawska** [comment]
Still happening

**Comment by DonHaul** [comment]
Fixed, can I close the issue?
