### ISSUE TITLE
Add more ordering options

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#531]
We should have the same ordering options as in old Holdingpen:
- best match
- relevance prediction (asc)
- relevance prediction (desc)

<img width="322" alt="Screenshot 2024-08-14 at 10 55 28" src="https://github.com/user-attachments/assets/4dc3cb23-3f8a-4dd8-aaed-361c285f4e1b">

**Comment by drjova** [comment]
TECH NOTES:
We only need to add the following for the moment:
 
* `bestmatch` is based on the `_score` field on OpenSearch, double check with documentation of opensearch


NOTE:
* `relevance` is no applicable yet, because it's related to classifier and hep data.

**Comment by DonHaul** [comment]
Configuration of `next` as a reference:
This is the configuration of next https://github.com/inspirehep/inspire-next/blob/d20c905fe9c0859749b490278b2549a561c2cb86/inspirehep/config.py#L1385-L1425
