### ISSUE TITLE
Connect Delete button in Author detail page

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#533]
After https://github.com/cern-sis/issues-inspire/issues/532 is done, connect `Delete` button in _Danger area_ section to endpoint.

**Comment by drjova** [comment]
Needs #532

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**

1. Create new component ```DeleteWorkflow.tsx``` in ```/holdingpen-new/components``` directory. The component should  receive workflow id as props and contain ```<Button className="font-white bg-error">Delete</Button>``` that opens confirmation modal. On confirming, it should dispatch ```deleteWorkflow``` action
2. In [holdingpen.ts](https://github.com/inspirehep/inspirehep/blob/5459598f81c56202d8c304153029fb5e51b144f3/ui/src/actions/holdingpen.ts) create a new action deleteWorkflow. It should send a DELETE request to ```/api/workflows/<id>``` endpoint and display success notification if delete was successful or error notification if not. After response from endpoint it should close modal.
3. In [AuthorDetailPageContainer.tsx](https://github.com/inspirehep/inspirehep/blob/c1dd620b71b3c28a01e71508684a4b60f043b7b8/ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx) line 188 use this component.
