### ISSUE TITLE
Workflow data is lost after workflow restart

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#545]
How to reproduce:

1. Submit or update author workflow
2. Click 'Accept'
3. Wait for the status to be 'completed'
4. Click 'restart workflow'
5. When the workflow status changes to 'running' the request data is gone, there's only `$schema` field left.

**Comment by DonHaul** [comment]
Issue comes from the fact that to restart, We delete all dags, and old data is forgotten.
