### ISSUE TITLE
Rename the holdingpen-new to backoffice

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#550]
Rename the `holdingpen-new` to `backoffice`

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES**:

1. in [routes.ts](https://github.com/inspirehep/inspirehep/blob/e338421a87fd298d4ff6bfecf263d1c5e493256a/ui/src/common/routes.ts) change ```HOLDINGPEN_NEW``` value to ```backoffice``` and rename variables accordingly.
2. Rename ```/holdingpen-new``` directory to ```backoffice```
3. Find all ```holdingpen-new``` variables and names across repository  and replace with ```backoffice```
4. Generate new svg for [LogoHoldingpen.tsx](https://github.com/inspirehep/inspirehep/blob/9a7b03c9f6ed36681d43300553305d697d35ab74/ui/src/common/components/Logo/LogoHoldingpen.tsx)
