### ISSUE TITLE
don't add invenio-classifier keywords to records

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#554]
Currently, we're adding keywords extracted by `invenio-classifier` in the article workflows to Literature records. These are only temporary, and are supposed to be later replaced by manually assigned keywords. However, DESY has stopped assigning those keywords manually, so we should stop putting the automated keywords in records too.
This requires removing the `prepare_keywords` workflow step from the `article` and `core_selection` workflows. 

Once that's implemented, we'll also need to clean up [existing records](https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=keywords.source%3Aclassifier).

**Comment by PascalEgn** [comment]
Instructions to cleanup after https://github.com/inspirehep/inspire-next/pull/4350 in deployed on prod:


Exec into primary postgres node, run `psql`, change db `\c inspirhep`, change table `\d records_metadata` and run the sql script:
```SQL
UPDATE records_metadata
SET json = (
    SELECT jsonb_set(
        json::jsonb,
        '{keywords}',
        (
            SELECT jsonb_agg(elem)
            FROM jsonb_array_elements(json::jsonb->'keywords') AS elem
            WHERE elem->>'source' != 'classifier'
        )
    )
)
WHERE json::jsonb->'keywords' IS NOT NULL
```

**Comment by michamos** [comment]
@PascalEgn it's a very bad idea to modify records in the DB directly, as many things are done at the application level during the update (reindexing this record and dependent records if needed, storing a new version in the `records_metadata_versions` table, triggering updates at ORCID and HAL if needed, etc.). This kind of large-scale metadata updates should be done using https://github.com/inspirehep/curation-scripts if possible or with custom code. In any case, it's not clear exactly how to clean this up in existing records due to merges where `classifier` metadata overwrote human-generated keywords. I'll update this once I have a clearer picture.
