### ISSUE TITLE
Fix monitoring for classifier

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#560]
We have a monitoring for [classifier](https://grafana.siscern.org/d/x2HDjXG4k/classifier-health?orgId=1) that it's not very useful. We have to see all http errors, memory usage and ideally send an error message to zulip to alert us.

**Comment by PascalEgn** [comment]
The current dashboard already displays https errors, it's just that there are none. The latest problem we had with requests timing out when using the endpoint, was related to a dead pod/node. To prevent this I guess we could introduce a liveness and/or readiness probe to the pods. 


I've prepared an example dashboard that would at least give us some more information about response time and memory usage:
![Image](https://github.com/user-attachments/assets/dd27480d-cfcb-4234-8d96-d0ba9e9baa80)

Regarding alerts, I guess we could alert in case a pod exceeds a response time threshold or memory usage. Something like the amount of API calls in the last 24h is as far as I know, very fluctuation to not really practical.

**Comment by PascalEgn** [comment]
Updated Grafana Dashboard: https://grafana.siscern.org/d/0TkuXReSz/classifier-prod?orgId=1&refresh=5s

**Comment by PascalEgn** [comment]
Added [liveness probe](https://github.com/cern-sis/kubernetes/blob/master/classifier/base/deployment.yml#L36-L43) to classifier pods.
