### ISSUE TITLE
From detail page, add a link always to point to running dags on airflow

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#561]
We should add a link to the running dags on the detail view. We can add a box below the snow tickets and be visible only for admins. The link should be similar with the error link.

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**

1. In [AuthorDetailPageContainer.tsx](https://github.com/inspirehep/inspirehep/blob/0d73daaa136bda9f7ea3d433e28c1da883768c87/ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx) line 331 add new `<ContentBox />` with subTitle prop "Running dags". It should only be visible if the user role is superuser or admin. It should display a link to running dag as follows `https://workflows.inspire.dev.siscern.org/dagrun/list/?_flt_0_run_id=<id>`

**Comment by drjova** [comment]
@karolina-siemieniuk-morawska there is an issue with this: 

![Image](https://github.com/user-attachments/assets/969ffe38-bc92-48af-a5ad-6dcea2d9953a)

It displays a `null` in front, and maybe it will be better UX to add a button? Because just display the UUID it's weird, WDYT?
