### ISSUE TITLE
Unify repos to either use master or main as default

### ISSUE THREAD

**Issue by PascalEgn** [cern-sis/issues-inspire#566]
We should decided on the naming, either use master or main for the default repo. 
More info on setting it on org level: https://docs.github.com/en/organizations/managing-organization-settings/managing-the-default-branch-name-for-repositories-in-your-organization

**Comment by drjova** [comment]
We can go with master, to be in-line with all the older packages.

**Comment by drjova** [comment]
no just the code

**Comment by PascalEgn** [comment]
As backoffice is now moved into the inspire monorepo. The only repo that is maintained only by us is: https://github.com/inspirehep/inspire-completness-check

Other repos that received changes "quite recently" are https://github.com/inspirehep/desy-harvest-scripts and https://github.com/inspirehep/data-analysis . Both of them receive commits from people outside the section and are not really used at the moment, so I would just leave their default branch "main"...

**Comment by PascalEgn** [comment]
Added master branch to https://github.com/inspirehep/inspire-completness-check, but cant delete main as its set as the default branch on the repo...

Some admin (@drjova ) please follow https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch to change the default branch to master (and delete main or ping me to delete it...)

**Comment by drjova** [comment]
@PascalEgn I think I cannot do it for all at the same time

**Comment by PascalEgn** [comment]
For the existing one (https://github.com/inspirehep/inspire-completness-check) you need to change it in the repo settings as described in [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch)  (or just rename the main branch to master in the GitHub ui as described [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch))


For new repos, you can change the default branch naming for our organization as described [here](https://docs.github.com/en/organizations/managing-organization-settings/managing-the-default-branch-name-for-repositories-in-your-organization)

**Comment by drjova** [comment]
@PascalEgn thanks for the summarized google search that I should have done 😅
