### ISSUE TITLE
Improve the monitoring of the services

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#568]
Add similar grafana dashboards for the following services:

- [ ] #569
- [x] #570
- [ ] #571
- [x] #572

**Comment by DonHaul** [comment]
Should be added to here somehow https://grafana.siscern.org/?orgId=1

**Comment by drjova** [comment]
@DonHaul @PascalEgn already worked on it

**Comment by DonHaul** [comment]
plotextract to be skipped
disambiguation to be skipped -  metrics : `disambiguation_changed_signatures_created` `disambiguation_changed_signatures_total`
