### ISSUE TITLE
Add Validation Endpoint for Records in InspireHEP

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#574]
We need to add a validation endpoint to the InspireHEP service to validate different types of records, specifically for author workflows. The endpoint should accept a record as a payload and validate it according to the specified type.

**TECH NOTES**

- Add a new endpoint in the class AuthorWorkflowViewSet(viewsets.ViewSet) located [here](https://github.com/inspirehep/backoffice/blob/fd58651fd77f00d4337f142830b71fb938933d0f/backoffice/backoffice/workflows/api/views.py#L107).
- The endpoint should be a POST request to `/api/workflows/authors/validate`.
- The endpoint should receive a record as the payload and perform validation using the `get_validation_errors` method from the `inspire_schemas.utils` package (ensure inspire_schemas is installed). You can reference the usage of this method in the record class [here](https://github.com/inspirehep/inspirehep/blob/63e39ae60d31e6dfd0250e784fe4f46e36ed8da5/backend/inspirehep/records/api/base.py#L74).
- Integrate the validation check when creating or updating an author workflow.
- Update the record editor to use this new endpoint instead of the existing /validate_workflow endpoint for author submissions.

**Expected Behavior:**

- If the record validation fails, the endpoint should respond with a 400 status code and include a payload of errors.
- If the validation passes, the endpoint should respond with a 200 status code.

**Acceptance Criteria:**

-  Endpoint /api/workflows/authors/validate is implemented and functional.
-  Endpoint correctly validates records based on their type.
-  Returns 400 with validation errors if validation fails.
-  Returns 200 if validation is successful.
-  Validation check is added for create/update operations in author workflows.
-  The record editor is updated to use the new validation endpoint.
-  Unit tests are written for the new endpoint to ensure proper validation behavior.

**Comment by PascalEgn** [comment]
We first have to make some changes to inspire-schemas 🫠  pyyaml and urllib3 versions need to be bumped in order to use it in inspire backoffice...

**Comment by PascalEgn** [comment]
Added validation endpoint in https://github.com/inspirehep/backoffice/pull/115

I think it makes sense to wait for https://github.com/inspirehep/inspirehep/pull/3246, to add the validation call in record editor
