### ISSUE TITLE
Create UK curation tickets for published papers too

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#576]
Currently we're creating UK curation tickets only for arXiv article workflows. This should be extended to published workflows, along the same lines as what has been recently been done for Germany in https://github.com/inspirehep/inspire-next/pull/4351.

**Comment by PascalEgn** [comment]
@michamos So we should check records for `"\b(UK|United\s+Kingdom|England|Scotland|Northern\s+Ireland)\b"` in the `raw_affiliations` and add them to the `UK_curation` queue/functional category if the regex matches?
