### ISSUE TITLE
Investigate if we can add validation to django serializers

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#578]
JSONSchema validation is currently implemented as an additional step in the views and endpoints within the backoffice.

**Task**
Explore the possibility of integrating the JSONSchema validation directly into the [DRF serializer](https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/api/serializers.py#L70), specifically for the [data](https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/models.py#L25) field.

**Acceptance:**
If integration is feasible, JSONSchema validation should:

- Raise validation errors in the same manner as Django REST Framework (DRF) serializers.
- Maintain consistency with existing validation patterns within the project.

**Comment by DonHaul** [comment]
An example of how to add custom validation:
https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/api/serializers.py#L71

**Comment by PascalEgn** [comment]
Changes contained in: https://github.com/inspirehep/inspirehep/pull/3272
