### ISSUE TITLE
add book publication information to LaTeX formats

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#58]
Currently we don't display book publication information in LaTeX citation formats (we do in BibTeX). We need to add the following information for records with `book` in  `document_type`:
* `{publisher}, {year},` taken from `publisher` and `date` from the first element of the `imprints` field (if one of those is missing, no middle comma)
*  formatted ISBN taken from the first element of `isbns.value`, formatting should use the same logic as in https://github.com/inspirehep/inspirehep/blob/a31aae6d3664be8071e2dcf6dd26ff7e49d6246e/backend/inspirehep/records/marshmallow/literature/bibtex.py#L322-L326. This should appear before other identifiers such as arXiv or DOI.

For example, LaTeX (EU) format of https://inspirehep.net/literature/758115 should be
```
%\cite{Kiritsis:2019npv}
\bibitem{Kiritsis:2019npv}
E.~Kiritsis,
%``String theory in a nutshell,''
Princeton University Press, 2019,
ISBN 978-0-691-15579-1
%60 citations counted in INSPIRE as of 01 Jun 2022
```

**Comment by drjova** [comment]
@michamos if there is no `imprints` but there `isbns` do we still display the ISBN?

**Comment by michamos** [comment]
good question! I would say yes.

**Comment by nooraangelva** [comment]
**TECH NOTES**

- add to [schema](https://github.com/inspirehep/inspirehep/blob/a31aae6d3664be8071e2dcf6dd26ff7e49d6246e/backend/inspirehep/records/marshmallow/literature/latex.py) values and methods for ```publisher``` and ```isbns```
- publisher -> {[publisher](https://github.com/inspirehep/inspirehep/blob/a31aae6d3664be8071e2dcf6dd26ff7e49d6246e/backend/inspirehep/records/marshmallow/literature/bibtex.py#L280-L281), year}  if one of those is missing, no middle comma
- year -> ```imprint_date = get_value(data, "imprints.date[0]")```
- isbns -> [ref function](https://github.com/inspirehep/inspirehep/blob/a31aae6d3664be8071e2dcf6dd26ff7e49d6246e/backend/inspirehep/records/marshmallow/literature/bibtex.py#L321-L330)
- update [template](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/backend/inspirehep/records/serializers/templates/latex_template.tex) with the new info (use Micha's example as reference)
- Create tests [here](https://github.com/inspirehep/inspirehep/blob/ff01a96f7100f7693bbed02f52047020979f31a2/backend/tests/integration/records/serializers/test_latex.py) for all cases (only the other one, both, none of them)
- possibly update rest of the latex tests with the new data, if needed. (ask first just in case)
