### ISSUE TITLE
Refactor Workflows by Type and Update Endpoints

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#582]
As we plan to introduce more workflow types in the backoffice, we need to refactor the current structure to better separate workflows by type. This involves creating dedicated Django apps for each workflow type, updating models, serializers, API endpoints, and ensuring changes are reflected in OpenSearch and the UI.

**Separate Workflow Types:**

- [x] Create a separate Django app for each type of workflow (starting with authors).
- [x] Move the existing Workflow model under the authors app.

**Update API Endpoints:**

- [x] Change the current workflows endpoint from /api/workflows to /api/workflows/authors.
- [x] Ensure all new workflow types will have dedicated endpoints under /api/workflows/{type}.

**Serializer and Model Refactoring:**

- [x] Separate serializers for each workflow type.
- [x] Ensure that models are properly refactored and cleaned, removing unnecessary components like core that are no longer relevant, for example [core](https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/models.py#L31) for authors.

**OpenSearch Index Update:**

- [x] Update Elasticsearch indices to reflect the new workflow structure.
- [x] Ensure the indices are properly aligned with the refactored models and endpoints.

**UI Update:**

- [ ] Ensure the UI is updated to call the new API endpoint /api/workflows/authors for author workflows.
- [ ] Test and verify that the UI behaves correctly with the new structure.

Acceptance:
A more modular workflow system with dedicated apps, serializers, and endpoints for each workflow type. The new /api/workflows/authors endpoint should be fully functional, with corresponding updates in Elasticsearch and the UI.

**Comment by DonHaul** [comment]
should `is_update` be removed?

**Comment by DonHaul** [comment]
informations in the `data` field is currently being dynamically generated should it be specified which fields we actually want to index?
