### ISSUE TITLE
Rename backoffice-repo to backoffice

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#586]
we should move backoffice and workflows on the root:

backend
backoffice
record-editor
worfklows
ui

etc.

**Comment by DonHaul** [comment]
with this change we will have a chain of 3 folders names backoffice. i.e. `inspirehep/backoffice/backoffice/backoffice`. Should we do any other modifications? 
- maybe rename the `backoffice` django app to something else?

**Comment by DonHaul** [comment]
https://pycqa.github.io/isort/docs/configuration/config_files.html#supporting-multiple-config-files-in-single-isort-run

https://docs.astral.sh/ruff/configuration/#config-file-discovery
