### ISSUE TITLE
remove core deselection workflow

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#59]
since https://github.com/inspirehep/inspire-next/pull/4184, the core deselection workflow referenced in https://github.com/inspirehep/inspire-next/blob/345e47f5cc3c5c0ee334fd5b4f4e2b9d4688abec/inspirehep/modules/workflows/workflows/article.py#L601-L609 is not needed any longer and can be removed (as well as all the existing holdingpen entries for this workflow in DB/ES).

**Comment by MJedr** [comment]
**TECH NOTES**
* Remove [the workflow](https://github.com/inspirehep/inspire-next/blob/345e47f5cc3c5c0ee334fd5b4f4e2b9d4688abec/inspirehep/modules/workflows/workflows/article.py#L601-L609) and all the leftovers in the code (so the functions that create it and all the things containing `NonCoreSelection` class).
* Write a query (es or db) which will select all the workflows of this category (`non_core_selection`) and will remove them (query and deletion should be executed in the pod).
