### ISSUE TITLE
Add experiments submission - frontend

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#6]
The form should be accessible only to curators (and be visible in the `submit` dropdown only to them) and contain the following fields:
* Type (required): corresponds to `project_type` with the 3 possible values from the enum
* Legacy name (required): populates `legacy_name`

After submission, the newly created experiment should open in the record editor.

**Comment by drjova** [comment]
@michamos could we check which fields are necessary for the curators?

**Comment by MJedr** [comment]
**TECH NOTES**

1. Create a form schema
2. Create following components - form, submission + success page
3. Create a submission container
4. Define route for submission [here](https://github.com/inspirehep/inspirehep/blob/master/ui/src/common/routes.js)
5. Add route for submission [here](https://github.com/inspirehep/inspirehep/blob/master/ui/src/submissions/index.jsx)
6. Add the menu item [here](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/common/layouts/Header/HeaderMenu.jsx#L69) and pass make it visible only for curators - that will require passing a prop from `HeaderMenuContainer` taken from state `isCatalogerLoggedIn: isCataloger(state.user.getIn(['data', 'roles’]))`
