### ISSUE TITLE
change arXiv URLs in next

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#600]
Currently we're using `export.arxiv.org` to download files from arXiv, but that server is overloaded. Following a call with the arXiv CTO, they will whitelist our IPs and we should use the main `arxiv.org` domain for all endpoints except OAI-PMH harvesting. This requires overriding the config keys in https://github.com/inspirehep/inspire-next/blob/ff47b1c64fe8b2c74574f66b13cf33990a3ff3a6/inspirehep/config.py#L1235-L1237 in https://github.com/cern-sis/kubernetes/blob/master/next/base/config/inspirehep.cfg to use the correct domain.

**Comment by DonHaul** [comment]
still no response from charles

**Comment by DonHaul** [comment]
Nice, i guess we can just overwrite it in `inspire-next` itself instead of `kubernetes`
