### ISSUE TITLE
Prepare hep for data & software

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#611]
# Add Support for `Data` Records  

**Description**:  
Implement support for `Data` records in INSPIRE, including API endpoints, search mappings, and necessary configurations.  

- [x] Make sure that we have citations for Data, as we do on https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/api/experiments.py
- [x] Add simple facts as we do on experiments https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/config.py#L416-L428
- [x] Add tests
---

### **Acceptance Criteria**  
- The `/api/data` endpoint returns valid responses, and facets function as expected.  
- The `importer demo-records` command successfully imports demo records for `data`.  
- `Data` records support citations, similar to `Experiments` and `Literature`.  
- Ensure that creating and updating record via an API works

**Comment by DonHaul** [comment]
experiments doesn't seem to have citation, basing it on the literature
https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/api/literature.py

**Comment by DonHaul** [comment]
citations already being tested in `test_data_citation_count_property`

test_views_data.py is testing updtates with `test_data_application_json_put` and 

there seems to be no tests for experiments put and post actions. - added for authors
