### ISSUE TITLE
fix bugs in new author workflow

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#614]
Testing of the new workflow by @michamos identified issues that should be fixed before further testing with outside curators

- [x] **accepted with curation puts workflow in error**: see https://inspirebeta.net/backoffice/5e4d9efe-7a01-4d56-9f13-383e14e20e1c
- [x] **SNow ticket handling is wrong**:  on https://inspirebeta.net/backoffice/5e4d9efe-7a01-4d56-9f13-383e14e20e1c, the [created ticket](https://cerntraining.service-now.com/nav_to.do?uri=/u_request_fulfillment.do?sys_id=85b13fb387f91210225886640cbb35a6) is wrong on several accounts ([compare with prod](https://cern.service-now.com/u_request_fulfillment.do?sys_id=ceb921fe472d8650ff618f1c736d43d6&sysparm_view=tabs_new&sysparm_record_target=u_request_fulfillment&sysparm_record_row=1&sysparm_record_rows=149&sysparm_record_list=active%3Dtrue%5Eu_functional_element%3Dea56eb930a0a8c0a0004af7b268a0987%5Eu_functional_category%3D6f576f151b822150e823a71eab4bcbd7%5Eassigned_toDYNAMIC90d1921e5f510100a9ad2572f2b477fe%5EORassigned_toISEMPTY%5EORassigned_to%3Dce1dd215873b951069c063990cbb35a7%5EORDERBYsys_created_on%5EORDERBYsys_id)): the title is incorrect, the functional category is incorrect, the description contains only a template but no payload, the initial ticket for the curator before the message for the user is missing, the user is not in the watchlist (and possibly more)
- [x] **author update is stuck in `running`**: https://inspirebeta.net/backoffice/10320bc2-d031-4834-824f-d5c2f4453fb8
- [x] **page state in search is not part of the URL**: this prevents linking of specific pages. Selection of facets and search query should be part of URL. This is probably not a blocker for authors (TBC), but should be fixed before adding other collections to the new backoffice.
- [x] **page state is shared between multiple tabs**: if you open two tabs, first one, say, with new authors, the other with author updates, then refresh the first tab, you'll get the content of the second tab
- [ ] **submission time (as opposed to date) is not visible in the metadata**: it would be good to make the submission time visible too and order by full date-time. Probably not a blocker for authors.
- [x] **changes take a long time to be visible**: after approving an author, it took ~20s before it was displayed as `running` instead of `approval`. This is confusing, would it be possible to change the state immediately (potentially to something like `waiting to be run` if it takes some time for the workflow to start again)?

**Comment by DonHaul** [comment]
1. api was not had been updated. Fixed by 
2. awaiting e-group to check format.
3. update dag was not turned on by default. check why

**Comment by michamos** [comment]
@DonHaul here are screenshots of service now

backoffice QA
![Image](https://github.com/user-attachments/assets/ebee82b6-7d8d-4bb3-bf2e-9bf3996789bd)

prod
![Image](https://github.com/user-attachments/assets/48252f34-4e1b-480d-beaa-3f4b29e8280d)

**Comment by drjova** [comment]
@DonHaul thank you, could you please make a PR for the 1st? As for the 3rd one, yes let's enable it for dev for now.
