### ISSUE TITLE
create an INITIAL workflow status

### ISSUE THREAD

**Issue by DonHaul** [cern-sis/issues-inspire#618]
Currently once a new workflow is created it is set imediately to true.
This can be misleading as the workflow can be in a queue for sometime before its actually picked up.

as such I propose we create this new `INITIAL` state, similar to how we have it in the current holding pen.

https://github.com/inspirehep/inspirehep/blob/master/backoffice/backoffice/authors/constants.py#L21

**Comment by drjova** [comment]
Created Processing status https://github.com/inspirehep/inspirehep/commit/8bb2a6a129b740e05eb9290eae9dcaf2f064acb4
