### ISSUE TITLE
fulltext: listen to sigterm signal and log information about the failing reocrds

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#64]
Collect more information why the workers are OOMing, great resource is the following

https://stackoverflow.com/questions/18499497/how-to-process-sigterm-signal-gracefully

**Comment by MJedr** [comment]
TECH NOTES:
1. Add the class for gracefull killing workers same as [here](https://stackoverflow.com/a/31464349/13207632). The handler for the frame might look similar to this:
```
import signal

def handler(signum, frame):
    LOGGER.error('Worker killed', error_type=frame.f_exc_type, error_value=frame. f_exc_value, traceback=frame.f_exc_traceback)
```
2. Add it to the fulltext batch indexing task as specified [here](https://stackoverflow.com/a/31464349/13207632)
