### ISSUE TITLE
don't strip MathML tags in harvesting

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#65]
We currently strip MathML tags in titles in JATS and Elsevier parsers in Hepcrawl. We should stop doing that and make sure the titles containing MathML are correctly displayed on the UI.

**Comment by drjova** [comment]
@michamos it doesn't seem that we are stripping on [Elsevier](https://github.com/inspirehep/hepcrawl/blob/master/hepcrawl/parsers/elsevier.py#L418) and [JATS](https://github.com/inspirehep/hepcrawl/blob/master/hepcrawl/parsers/jats.py#L325) maybe I'm missing something?

**Comment by nooraangelva** [comment]
**TECHNOTES:** 
- Check first the tag in title [here](https://github.com/inspirehep/hepcrawl/blob/master/hepcrawl/parsers/elsevier.py#L418) and [here](https://github.com/inspirehep/hepcrawl/blob/master/hepcrawl/parsers/jats.py#L325) if [MathML](https://www.w3.org/TR/MathML2/chapter2.html) is in tags don't use ```string()```  
- Create test [here](https://github.com/inspirehep/hepcrawl/blob/fd8c0ab6ddf471ced2ad5c0545a60bf4e46e1157/tests/unit/test_parsers_jats.py) Add a document with a title that contains MathML- [reference test](https://github.com/inspirehep/hepcrawl/blob/fd8c0ab6ddf471ced2ad5c0545a60bf4e46e1157/tests/unit/test_parsers_jats.py#L98-L108) 
- UI test [here]() - [reference test]() WORKING ON THIS...

**Comment by drjova** [comment]
@michamos could you please give us some records to test on QA when this fix is deployed there?
