### ISSUE TITLE
Create backend for claiming in literature detailed view

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#68]
Create new functionality to make claiming paper on literature detail view possible. 

* Related to: https://github.com/cern-sis/issues-inspire/issues/45

**Comment by MJedr** [comment]
**TECH NOTES**
* add a new function to assign/utils.py which will get all the authors from the paper and then it will check if there is an unambiguous match for names with any of authors in literature. If there is no unambiguous match or no match at all return False. The function should check for name compatibility in the following order:
  - author last name and lit author last name
  - author first name initial and last name and lit author first name initial and last name
  - author full name and lit author full name
* In literature ui serializer [here](https://github.com/inspirehep/inspirehep/blob/88f767ea8d5e7fc4bb547d7a578542b9d27cb315/backend/inspirehep/records/marshmallow/literature/ui.py#L288) check if the request comes from `authors` url or `literature`. If it comes from `authors` leave current check but if it's from literature use a new function to assign `can_claim` value
