### ISSUE TITLE
Journal collection: Add number of papers and embed view of literature papers in the detail view

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#71]
## Number of papers
![image](https://user-images.githubusercontent.com/4287772/175293406-319c9059-6728-4e5f-ad67-5b6487f0334f.png)

## Embed view of literature papers in the detail view
![image](https://user-images.githubusercontent.com/4287772/175293387-e0914aec-3def-43f9-8142-0f3b2084bf73.png)

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:** 

1. Create ```<JournalPapersContainer />``` file with ```<JournalPapers />``` component. It should contain 
``` <LiteratureSearchContainer
                namespace={JOURNAL_PAPERS_NS}
                baseQuery={baseQuery}
                baseAggregationsQuery={baseAggregationsQuery}
                noResultsTitle="0 Journal papers"
                embedded
          />```
2. ```baseAggregationsQuery``` and ```baseQuery``` to be determined after the backend is ready.

**Comment by MJedr** [comment]
actually base query & base aggregations we don't need any backend change (it's based on ES). It should be similar to this https://github.com/inspirehep/inspirehep/blob/master/ui/src/experiments/containers/ExperimentPapers.jsx or this https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/containers/AuthorPublicationsContainer.jsx
