### ISSUE TITLE
Student-advisor table has primary key than disable adding the same advisor for more than one degree 

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#79]
https://sentry.sis.cern.ch/inspire/hep/issues/39083/?query=is%3Aunresolved
The primary key constraint for StudentsAdvisors table consist of advisor_id and student_id.
```
In [12]: inspect(StudentsAdvisors).primary_key                                                                                                                                                   
Out[12]: 
(Column('advisor_id', UUIDType(length=16), ForeignKey('records_metadata.id'), table=<students_advisors>, primary_key=True, nullable=False),
 Column('student_id', UUIDType(length=16), ForeignKey('records_metadata.id'), table=<students_advisors>, primary_key=True, nullable=False))
 ```
It might happen that the student had the same advisor for different degrees, example:
```
"advisors": [
{
"curated_relation": false,
"degree_type": "phd",
"hidden": false,
"name": "Rezzolla, Luciano",
"record": {
"$ref": "https://inspirehep.net/api/authors/991880"
}
},
{
"curated_relation": false,
"degree_type": "master",
"hidden": false,
"name": "Rezzolla, Luciano",
"record": {
"$ref": "https://inspirehep.net/api/authors/991880"
}
}
],
```
We should modify the primary key by adding a degree type there for example.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Add a default value for missing degree type (`unknown`) [here](https://github.com/inspirehep/inspirehep/blob/1bf4cf5f2fe7b565f3b643c35f1cafe6c1e0b974/backend/inspirehep/records/api/mixins.py#L616)
2. Add `unknown` to enum [here](https://github.com/inspirehep/inspirehep/blob/1bf4cf5f2fe7b565f3b643c35f1cafe6c1e0b974/backend/inspirehep/records/models.py#L233)
3. Add a primary key argument to the [degree type column](https://github.com/inspirehep/inspirehep/blob/1bf4cf5f2fe7b565f3b643c35f1cafe6c1e0b974/backend/inspirehep/records/models.py#L264) and `nullable=False` constrain
4. Migrate alembic (don't forget to do it on qa & prod later)
5. [Here](https://github.com/inspirehep/inspirehep/blob/8910a2ca976d526640b4fcfba42479116b9952fa/backend/inspirehep/records/marshmallow/authors/base.py#L41) if the degree type is `unknown` replace it with None

**Comment by MJedr** [comment]
**TECH NOTES (modification)**
1. Remove primary key constraint from the students_advisors table
2. Add an autogenerated primary key `id = db.Column(db.Integer , primary_key=True)` to the `students_advisors` table

**Comment by drjova** [comment]
Unfortunately, the alembic recipe is not correct and we had to revert back the changes from production.
