### ISSUE TITLE
bump react

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#8]

**Comment by karolina-siemieniuk-morawska** [comment]
**Tech notes**:
There are no discrepancies between React 16 and latest React which could be a blocker for us, I recommend updating React and necessary dependencies to the latest version.

**Comment by karolina-siemieniuk-morawska** [comment]
Upgrading React will require significant changes in the codebase (like choosing a new test utility to replace Enzyme, which only supports React =<16).

**Comment by karolina-siemieniuk-morawska** [comment]
Bumped to 17.0.2
