### ISSUE TITLE
limit files to 100mb

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#82]
On hep we should limit the filesize to 100mb. When we create a record and an attached file is more than 100mb we should return an error, same for the REST response.

**Comment by nooraangelva** [comment]
**TECH NOTES**

- check file sizes [here](https://github.com/inspirehep/inspirehep/blob/97758097c5c995a1f6236d7c4e3cfee344254888/backend/inspirehep/records/api/literature.py#L367) (x < 100mb)
- if too big raise error, example:  ```raise MaxResultWindowRESTError("Something..."))```, create the error
- add tests [here](https://github.com/inspirehep/inspirehep/blob/595b90740c40a3ea3960d987e9262bd8aa884f21/backend/tests/integration/records/api/test_api_literature.py), [ref test](https://github.com/inspirehep/inspirehep/blob/595b90740c40a3ea3960d987e9262bd8aa884f21/backend/tests/integration/records/api/test_api_literature.py#L1003-L1054)
- add test [here](https://github.com/inspirehep/inspirehep/blob/595b90740c40a3ea3960d987e9262bd8aa884f21/backend/tests/integration/records/views/test_views_literature.py)
- [Reference PR](https://github.com/inspirehep/inspirehep/commit/a4ce47ff64b0d2c84ce14212933291f47e597fbd) (same idea)

**Comment by drjova** [comment]
@michamos should we fail records with larger than 100mb or just ignore the files?
