### ISSUE TITLE
Remove GRID links from institutions display

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#84]
GRID is dead and superseded by ROR, so we should stop displaying GRID links on the institution display, but still keep it in the record metadata for now.

**Comment by drjova** [comment]
@michamos do you have an example of an institution with GRID?

**Comment by michamos** [comment]
https://inspirehep.net/institutions/902725 :)

**Comment by karolina-siemieniuk-morawska** [comment]
Tech notes:

In institutions' [DetailPageContainer](https://github.com/inspirehep/inspirehep/blob/97758097c5c995a1f6236d7c4e3cfee344254888/ui/src/institutions/containers/DetailPageContainer.jsx#L109-L113) remove `<GridLink />`
