### ISSUE TITLE
keyerror `full_name` on cv format

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#90]
We get this [error](https://sentry.sis.cern.ch/inspire/hep/?query=url%3A%22https%3A%2F%2Finspirehep.net%2Fliterature%2F1779260%22) on `CV` format.

Example: https://inspirehep.net/api/literature/1779260?format=cv

**Comment by michamos** [comment]
Maybe related to the second author being a supervisor? I believe we handle those a bit differently.
