### ISSUE TITLE
Update Elsevier harvester for new API

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#96]
Elsevier have updated their API (Consyn 2.0) and their atom feeds are now behind HTTP basic auth. We need to update https://github.com/inspirehep/hepcrawl/blob/2a4144bf4f4eb8065e7dd826f63d51e79917cc72/hepcrawl/spiders/elsevier_spider.py#L126-L128 to support HTTP basic auth and to pass the correct username and password there.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Add `elsevier_user` and `elsevier_password` to the args passed to the spider
2. Encode base64 user and password (`f"{elsevier_user}:{elsevier_password}"`, that should be encoded)
3. Add authorization to the [request](https://github.com/inspirehep/hepcrawl/blob/2a4144bf4f4eb8065e7dd826f63d51e79917cc72/hepcrawl/spiders/elsevier_spider.py#L126-L128) headers, so `headers={'Authorization': 'Basic ' + base64encodeddata}
4. Update sealed secrets in k8s - add [here](https://github.com/cern-sis/kubernetes/blob/master/next/environments/inspire-qa/sealedsecrets/next-creds.yml) `ELSEVIER_USER` and `ELSEVIER_PASSWORD` and remove `ELSEVIER_BATCH_FEED_KEY`
5. Update spider kwargs [here] - add `elsevier_user` and `elsevier_password` (should be taken from env)

**Comment by michamos** [comment]
I think the key is still needed, but they've added HTTP Basic auth on top of that.
